import type { BlogPost } from "@/lib/blog-posts";

export const CURRENT_BLOG_POSTS: BlogPost[] = [
  {
    slug: "behind-the-print-knowing-when-to-stop",
    title: "Behind the Print: Knowing When to Stop",
    excerpt:
      "Retouching two ShutterFest photographs of Claire Rieger and a snake with Reblum — and relearning that restraint, not another slider, is what actually finishes a photograph.",
    date: "2026-09-27",
    seoTitle: "Behind the Print: Knowing When to Stop | Behind The Print",
    metaDescription:
      "John Guest on restraint in retouching, testing Reblum on two Eve-and-snake photographs of Claire Rieger from ShutterFest 2024, and why the print still gets the final say.",
    tags: [
      "Behind The Print",
      "Portrait Photography",
      "Retouching",
      "ShutterFest 2024",
      "Reblum",
      "Fine Art Printing",
    ],
    image: "https://g.tlcdn.com/gen/c17afd37cb174ad294669d54f8dc9de3.webp",
    imageAlt:
      "Model Claire Rieger dressed as Eve, holding a red apple in one raised hand while a large snake drapes over her opposite shoulder and arm, wearing a leaf-and-floral bra top with an olive-green skirt, photographed against a dim red-lit backdrop with white columns",
    imageCaption:
      "Claire Rieger during the Day Zero event at ShutterFest 2024. Snake courtesy of Michael Beran.",
    imageCredit:
      "Photograph by John Guest, Photography Fit 2 Print. Model: Claire Rieger. Snake: Michael Beran. Event: ShutterFest 2024 — Day Zero.",
    imageWidth: 1333,
    imageHeight: 2000,
    imageUnoptimized: true,
    content: [
      "I’ve been retouching photographs long enough to know that one of the most dangerous things you can have is another slider.",
      "There is always something else you can fix.",
      "Another blemish. Another shadow. Another little distraction. Another adjustment that seems harmless by itself. Keep going long enough and eventually you can polish all the life right out of a photograph.",
      "I was thinking about that while working on these photographs of model Claire Rieger, made during the Day Zero event at ShutterFest 2024, with the snake provided by Michael Beran.",
      "The setup is one I’ve photographed more than once.",
      "Eve. The apple. The snake.",
      "It’s such a classic triangle that there really isn’t much need to explain it. Temptation, beauty, danger, curiosity, choice. Put those three elements together and we already bring thousands of years of storytelling into the photograph with us.",
      "What I’ve discovered is that it’s also wonderfully repeatable.",
      "Different model. Different snake. Different expression. Different photographer standing behind the camera.",
      "And somehow, every model and snake combination I’ve photographed has given me something beautiful.",
      "That’s what makes me want to return to a theme rather than simply repeat a picture. I already know the ingredients. What I don’t know is what will happen when this particular person, this particular animal, the light and that particular moment all come together.",
      "Claire gave me something especially interesting here.",
      "The apple is sitting quietly in one hand while this substantial living creature is draped across the other. There is a lot happening in the frame, but her expression doesn’t compete with any of it.",
      "She gives the photograph room.",
      "That became important when I started retouching.",
      "I’ve recently begun incorporating Reblum into my workflow. I’m still learning it, and I think that’s worth saying. I’m not interested in presenting myself as an expert on a piece of software I’m still getting acquainted with.",
      "What I can talk about is what I expect from a retouch.",
      "I don’t want software deciding what my photograph should become. The photograph has already been made. The light, expression, composition and moment are already there.",
      "My job now is to finish it.",
      "With Claire, I paid particular attention to her skin. I wanted polish without turning her into porcelain. I wanted her face to retain dimension. Her curls needed to remain curls. The flowers needed their texture.",
      "And that snake definitely needed to remain a snake.",
      "Look closely at the scales, patterns and highlights running across its body. They’re an important counterpoint to Claire’s skin, the flowers and the softness of her hair. Smooth everything indiscriminately and I would start destroying the very contrasts that make the photograph interesting.",
      "That is where restraint becomes part of retouching.",
      {
        type: "image",
        src: "https://g.tlcdn.com/gen/0a2e9d37f0fe4b04ad9f29ae89597b24.webp",
        alt: "Close portrait of Claire Rieger looking past the apple and snake toward something beyond the frame, snake draped over her shoulder, leaf-and-floral bra top visible",
        caption:
          "Claire isn’t looking at the apple or the snake. She’s looking somewhere beyond both of them.",
        credit:
          "Photograph by John Guest, Photography Fit 2 Print. Model: Claire Rieger. Snake: Michael Beran. Event: ShutterFest 2024 — Day Zero.",
        width: 1333,
        height: 2000,
        unoptimized: true,
      },
      "This second frame is the one that keeps pulling me back.",
      "It’s her eyes.",
      "Claire isn’t looking at the apple. She isn’t looking at the snake. She is looking somewhere beyond both of them.",
      "That tiny change creates an entirely different photograph for me.",
      "The first image feels like a question about temptation.",
      "The second makes me wonder whether the decision has already been made.",
      "And here’s the important part.",
      "Reblum didn’t create that.",
      "That happened between Claire, the snake, the environment, my camera and me when I pressed the shutter.",
      "The software came later.",
      "That distinction is becoming my test for AI-assisted tools in photography: Does the tool help me finish my photograph, or does it start trying to become the photographer?",
      "So far, what interests me about Reblum is the possibility of incorporating it into a process I already understand.",
      "Capture still matters. Light matters. Expression matters. Curation matters. Retouching matters. And knowing when to stop matters.",
      "The software can help with the labor.",
      "It doesn’t get the final say.",
      "That belongs to me.",
      "Eventually there is one more test these photographs have to pass.",
      ">> The Paper.",
      "I want to see those deep reds and blacks come out of my printer. The olive green. Claire’s skin against that darkness. Those soft pink flowers. And the extraordinary pattern of the snake moving through the composition.",
      "Because around here, an image isn’t finished simply because it looks good on a screen.",
      ">>> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
      "Model: Claire Rieger / Snake: Michael Beran / Event: ShutterFest 2024 — Day Zero / Photography: Photography Fit 2 Print / John Guest",
      "Disclosure: I’m a Reblum affiliate. If you decide to try Reblum through my affiliate link or code ([reblum.app/p/TID.2934](https://reblum.app/p/TID.2934)), I may receive a benefit from the referral. These are my photographs and my opinions about how Reblum fits into my own retouching workflow.",
    ],
  },
  {
    slug: "behind-the-print-learning-how-we-work",
    title: "Behind the Print: Learning How We Work",
    excerpt:
      "A look back at the early friction of building an AI-assisted photography workflow, and what changed once memory stopped being mistaken for knowledge.",
    date: "2026-09-19",
    seoTitle: "Behind the Print: Learning How We Work | Behind The Print",
    metaDescription:
      "John Guest reflects on the early friction of building an AI-assisted photography workflow, the difference between memory and knowledge, and where creative judgment still belongs to the photographer.",
    tags: ["Behind The Print", "Photography Workflow", "AI-Assisted Creativity", "Personal Reflection"],
    content: [
      "There was a point where all of this felt a lot more complicated than it does now.",
      "Not because the technology was necessarily difficult, but because we were still learning each other. I was learning what AI could actually help me with, what it was good at, what it was terrible at, and where I still needed to keep my own hands firmly on the wheel. At the same time, I was trying to figure out how to build something that supported my photography without turning the technology itself into the main attraction.",
      "There were some bumps. Actually, there were a lot of bumps. Files ended up in the wrong place. Instructions got misunderstood. Things I thought were obvious were not obvious at all. Sometimes the system moved too fast. Sometimes I expected too much. Sometimes I had to stop everything and say, “No. That is not what I meant.”",
      "And somewhere along the way, that became part of the process.",
      "What started as conversations about cameras, lighting, editing, and printing slowly became something more useful. We started building a working environment around the photography itself.",
      "Camera manuals stayed available when I needed to check a setting instead of trusting my memory. Lighting information became something we could return to rather than rediscover every time. Critiques started becoming less about whether someone “liked” the picture and more about what I was actually trying to accomplish. Intent, composition, light, color, texture, emotion, and print all became part of the conversation.",
      "The questions got better, and when the questions got better, the work started getting better too.",
      "One of the biggest lessons for me was learning that memory and knowledge are not the same thing. Just because a system remembers something does not make it true. Just because we discussed something three months ago does not mean it should become gospel.",
      "That realization changed the way I started thinking about this whole relationship.",
      "If Canon says something about the R5 Mark II, I want the Canon manual. If I am troubleshooting a lighting setup, I want the specifications and the results from the actual test. If I am reviewing competition work, I want the scorecard and the notes. If I am talking about what makes a photograph successful, then I want my own experience and judgment in that conversation too.",
      "And if AI is making an educated guess, I want to know that it is a guess.",
      "That distinction matters to me.",
      "Photography has always been full of opinion. Somebody likes contrast. Somebody else wants everything soft. Somebody wants more detail. Somebody thinks the crop should have been different. That is part of art.",
      "But technical facts are different. If I am going to build a workflow around something, I want to know where the information came from.",
      "Over time, that has become one of the strongest parts of what we are building together. I do not need AI to pretend it knows everything. I need it to help me organize what I know, find what I do not know, challenge me when something does not make sense, and stay out of the way when the creative decision belongs to me.",
      "That balance took some work. There were moments when I treated the technology like magic, and there were other moments when the technology reminded me very quickly that it was not. That is probably where some of the most important learning happened.",
      "The strengths started becoming obvious. AI is very good at helping me organize a messy idea. It is good at comparing information. It can help me research, and it can help me build a repeatable process so I do not have to reinvent the wheel every time.",
      "It can look at a photography problem from several directions and give me things to consider that I might have overlooked. But there are also places where I do not want it making the final decision.",
      "It was not standing there when the light changed. It did not see the expression before I pressed the shutter. It does not know why a photograph makes me stop walking through the house and stare at the print on the wall.",
      "Those decisions still belong to me.",
      "And somewhere in all of this, I noticed something else. A few of the things that once seemed odd to people, too deliberate or too much, started showing up around me in other forms.",
      "That made me smile.",
      "Not because I need credit for every idea that looks familiar. I do not. Influence does not always come with a receipt. But it reminded me that sometimes you have to live with your own ideas long enough for other people to see what you saw in them.",
      "You build in public. You repeat what matters. You keep shaping it until it sounds like you. Then one day, the thing people questioned starts appearing in other places.",
      "That does not mean they became you. It means the idea had weight.",
      "That may be the biggest victory in all of this. We did not build a system to replace the photographer. We built one to support him.",
      "The manuals have their place. The critique framework has its place. The score sheets have their place. The conversations have their place. And somewhere in the middle of all of it is still a man with a camera trying to make something meaningful.",
      "I like that because I have never believed photography was just about capturing an image. It is about intention, learning how to see, understanding your tools well enough that they stop getting in the way, making mistakes, recognizing them, and getting a little better the next time.",
      "And eventually, if we did our jobs right, it becomes something you can hold.",
      "A piece of paper with a memory on it.",
      ">>> Fit to capture. Fit to curate. Fit to print.",
    ],
  },
  {
    slug: "the-pitching-duel-continues",
    title: "The Pitching Duel Continues",
    excerpt:
      "Recognition can confirm that the work is connecting, but the deeper lesson is discipline: slowing down, protecting the person in the photograph, and letting the print reveal whether the job is truly finished.",
    date: "2026-09-17",
    seoTitle: "The Pitching Duel Continues | Behind the Print",
    metaDescription:
      "John Guest reflects on recognition, creative growth, and an evolving Fit 2 Print workflow using Lightroom, Evoto, Photoshop, and the final truth of the printed photograph.",
    tags: [
      "Behind The Print",
      "Portrait Photography",
      "Photography Workflow",
      "Evoto",
      "ShutterFest 2024",
      "Fine Art Printing",
    ],
    image: "/blog/the-pitching-duel-continues/Briana-Thomas-hero.jpg",
    imageAlt:
      "Black and white portrait of model Briana Thomas reclining in an ornate chair at ShutterFest 2024",
    imageCaption:
      "Briana Thomas at ShutterFest 2024. The photograph connected, but the lesson went deeper than the numbers.",
    imageCredit:
      "Photograph by John Guest, Photography Fit 2 Print. Model: Briana Thomas (@tiraleya). Makeup artist: Refine Beauty.",
    imageWidth: 1365,
    imageHeight: 2048,
    content: [
      "I wasn’t chasing recognition with this photograph. But I’d be lying if I said I never wonder, in those quiet spaces, whether all the years of shooting, editing, printing, studying light, studying people, and studying myself are making me better. Then something like this happens. A photograph I made starts getting seen. People stop. They look. They respond. I didn’t build a campaign around it or try to manufacture a moment. The photograph simply connected.",
      {
        type: "image",
        src: "/blog/the-pitching-duel-continues/Bri-instagram.jpg",
        alt: "Instagram notification celebrating more than 500 views and 944 views for John Guest’s black and white portrait of Briana Thomas",
        caption:
          "Recognition I wasn’t seeking outright, but maybe hoping for in those quiet spaces where I wonder.",
        credit: "Instagram recognition screenshot provided by Photography Fit 2 Print.",
        width: 1206,
        height: 2622,
        unoptimized: true,
      },
      "That feels like evidence of honed skill. And maybe I shot my shot. The funny thing is, I’ve had more shots like this lately. Enough that I’m beginning to realize the next evolution isn’t only about making better photographs. It’s also about becoming more disciplined with what happens after I press the shutter.",
      "I get excited by the home runs. I see a frame that hits and I want to run straight toward the finish line. But craftsmanship lives in the rest of the game too. Sometimes it’s a real head-to-head matchup, working deep into the pitch count and refusing to swing just because something is there.",
      "That means slowing down and attacking every megapixel with purpose. Looking at the transitions in the skin. The highlights. The shadows. Every instance of digital noise. The small distractions that may not matter on a phone but suddenly become very real when an image gets larger. More importantly, it means deciding what actually needs correcting and what deserves to remain exactly as it is. That distinction matters to me, especially when I’m photographing people.",
      "Lightroom is still where I establish the photograph: exposure, tone, color, composition, and the overall intent of the frame. Evoto has become another part of that refinement process. I use it for targeted skin work, localized corrections, cleanup, and some of the repetitive technical work that can pull attention away from the photograph itself. The software is powerful, but that doesn’t mean every slider needs to move. My responsibility is still to recognize the person in front of me and preserve what makes them unmistakably themselves.",
      "Photoshop gets called when the photograph needs surgery instead of medicine. And ultimately, the print tells me the truth. A photograph can look beautiful glowing from a screen and still expose every weak decision once it becomes ink on paper. That’s one reason printing remains part of my process. It forces me to look harder. It makes me accountable for the entire photograph rather than just the version somebody scrolls past online.",
      "This photograph of Briana Thomas was created during ShutterFest 2024 on April 4, 2024. Briana brought the presence. Refine Beauty handled the makeup artistry. I had the privilege of deciding where to put the light, when to press the shutter, and later, how far to take the photograph without taking anything away from the woman who made the frame work in the first place.",
      "So yes, I’m enjoying the love and the shine. But I’m paying even more attention to what it’s teaching me. I’m giving myself the space to grow.",
      ">> The pitching duel continues.",
      "Model: Briana Thomas / Instagram: [@tiraleya](https://www.instagram.com/tiraleya/) / Makeup Artist: Refine Beauty / Event: ShutterFest 2024 / Photographed: April 4, 2024",
      ">>> Fit to capture. Fit to curate. Fit to print.",
    ],
  },
  {
    slug: "see-it-in-color-before-you-kill-the-color",
    title: "See It in Color Before You Kill the Color",
    excerpt:
      "A strong black and white photograph should not begin with throwing the color away. I look first at what the color is giving me, then decide what needs to survive the conversion and eventually the print.",
    date: "2026-09-10",
    seoTitle: "See It in Color Before You Kill the Color | Behind the Print",
    metaDescription:
      "A Photography Fit 2 Print look at intentional black and white conversion, from reading the original color photograph to preserving skin, light, texture, expression, and ultimately making the print.",
    tags: [
      "Behind The Print",
      "Black and White Photography",
      "Portrait Photography",
      "ShutterFest 2026",
      "Intentional Photography",
      "Fine Art Printing",
    ],
    image: "/blog/see-it-in-color-before-you-kill-the-color/bw-portrait.jpg",
    imageAlt:
      "Black and white portrait photographed at Shutterfest 2026, framed by foliage",
    imageCaption: "The finished black and white interpretation.",
    imageCredit:
      "Photograph by John Guest, Photography Fit 2 Print. Model: Alec Reichert (@lexxluma).",
    imageWidth: 800,
    imageHeight: 1200,
    content: [
      "Sometimes a photograph tells you what it wants to be, but not immediately. Sometimes you have to live with it for a minute.",
      "I had a color portrait from Shutterfest 2026 that I liked. The light was doing what I wanted. The skin had warmth. The lace had texture and delicacy. There was softness in the pose without the image feeling weak, and her expression had that little bit of confidence and stillness that made me keep looking at it. The color version worked. The question was whether color was helping the photograph say what I wanted it to say, or whether it was simply one more thing asking for attention.",
      "That is where the black and white conversation started. Not with a preset or a button, but with the photograph.",
      "## Before I Take the Color Away, I Want to Know What It Is Giving Me",
      "The color photograph was already doing a lot of things well. Her warm skin sat against the burgundy of the dress, surrounded by layers of green foliage and cooler tones farther back in the frame. The colors gave me separation almost for free.",
      {
        type: "image",
        src: "/blog/see-it-in-color-before-you-kill-the-color/color-portrait.jpg",
        alt: "Original color portrait photographed at Shutterfest 2026 with burgundy dress and green foliage",
        caption:
          "The color photograph already worked. The question was whether color was still helping the photograph say what I wanted it to say.",
        credit:
          "Photograph by John Guest, Photography Fit 2 Print. Model: Alec Reichert (@lexxluma).",
        width: 800,
        height: 1200,
      },
      "Before converting anything, I want to understand what I would be giving up. In this photograph I cared about the softness of the skin, the shape created by the light, the delicacy of the lace, the transitions through the shadows and, most of all, the expression. Black and white drama by itself does not improve a photograph. If I lose the suppleness of the skin, bury the lace, flatten the face or make the light too aggressive, then I have not improved anything. I have just made it monochrome.",
      "## The Photograph Still Has to Feel Good",
      "Photographers can get distracted by channels, curves, black points and contrast and forget that the image still has to feel like something. I want skin to have life. I want the light to move across the body. I want lace to remain soft, fine and dimensional instead of becoming a hard white shape. I want shadow detail where I need it and darkness where it helps the photograph. I want the transition from highlight to shadow to feel natural. And I want the expression to remain the reason you stay with the image.",
      "Technique serves those priorities. Not the other way around.",
      "## Then I Start Looking at Tone",
      "Once I know what I am trying to protect, I start considering how the photograph will behave without color. Where are the deepest shadows? Where are the brightest highlights? How much separation exists between skin and lace, between the dress and the body, between the subject and the foliage? Which areas are being separated mostly by hue rather than brightness?",
      "That matters because red and orange information in the skin can later control how bright or dark that skin becomes. Greens in the foliage can be moved independently. The burgundy dress can become a completely different tonal value depending on how those channels are translated. Two things that look clearly different in color can collapse into nearly the same gray if I am not paying attention.",
      "Once I began thinking about the photograph in black and white, the color safety net disappeared. Skin needed to remain supple. Lace needed to stay delicate. The smoother fabric of the dress needed enough tonal difference that it did not become one flat shape. Her dark hair needed separation without turning into a solid mass, and the foliage still had to frame her without fighting for attention.",
      "## Black and White Does Not Fix a Color Problem",
      "I also look for things like mixed light, green bounce, magenta in the skin and chromatic aberration before I convert. Black and white does not suddenly make the underlying color information irrelevant. Some of it disappears visually, but the channel relationships still affect what happens when I begin mixing tones.",
      "If something needs correcting, I would rather deal with it while I can still see the cause. I am not trying to make a perfect color photograph just so I can throw the color away. I am preparing the file for the interpretation I actually want to make.",
      "## Then the Color Can Go",
      "When I finally convert, I want control over the original color channels. A Black & White adjustment layer in Photoshop or the Black & White Mix in Lightroom lets me decide how reds, oranges, yellows, greens, blues and other colors translate into gray. That means I can protect the skin, let the background fall away, hold detail in the lace and create separation selectively instead of simply throwing global contrast at the whole photograph.",
      "Global contrast is easy. Selective contrast is where the photograph starts becoming yours. Sometimes the skin needs to stay open while the background comes down. Sometimes the lace needs a little more presence. Sometimes the face needs almost nothing because the light already did the work. I am not moving sliders for drama. I am trying to preserve the things that made me stop on the image in the first place.",
      "## Why This One Became Black and White",
      "The color version was good. I could have finished it there. But the things I cared about most did not depend on color. They were shape, light, skin, texture, lace, expression and the quiet relationship between highlight and shadow.",
      "Most important was her expression. Take away the burgundy and the greens and there is less between the viewer and her face. Her eyes, the slight smile and the quiet confidence in the pose begin carrying more of the photograph. That was when I knew the conversion was giving me something rather than simply taking color away.",
      "The photograph felt quieter and more intimate. The lace became more about texture against skin. The light became more obvious without becoming louder. The skin could remain soft and alive. Her expression carried more weight because there was less competing with it. At that point, black and white stopped being an effect and became the interpretation I wanted.",
      "## And Eventually, It Has to Become a Print",
      "For Photography Fit 2 Print, that part is literal. I do not consider the photograph finished simply because it looks right on a monitor. A black and white image can fool you on a bright screen. Shadows can look richer than they will on paper. Tonal transitions can disappear. Lace separation can vanish. Skin that looks luminous on a backlit display can print too dark if the midtones are not carrying enough information.",
      "The print gets a vote. I want to see whether the light still moves the way I intended, whether the skin retains its suppleness, whether the lace remains lace instead of becoming a block of white, whether the blacks have weight without swallowing the photograph, and whether her expression is still the first thing that holds me. If the print says no, I go back. That is part of the craft.",
      {
        type: "image",
        src: "/blog/see-it-in-color-before-you-kill-the-color/print-still.jpg",
        alt: "Black and white portrait emerging as a physical photographic print",
        caption:
          "The final test: watching the black-and-white portrait come off the printer. This is where screen decisions become paper decisions.",
        credit: "Photography Fit 2 Print",
        width: 675,
        height: 1200,
      },
      "The camera gave me the photograph. The color file gave me the information. The black and white conversion gave me another interpretation. The print tells me whether I actually finished the job. That is why I try to see the color before I kill it.",
      "Model: Alec Reichert / Instagram: [@lexxluma](https://www.instagram.com/lexxluma/)",
      ">>> Fit to capture. Fit to curate. Fit to print.",
    ],
  },
];
