export interface BlogImage {
  type: "image";
  src: string;
  alt: string;
  caption?: string;
  credit?: string;
  width: number;
  height: number;
}

export interface BlogVideo {
  type: "video";
  src: string;
  poster: string;
  title: string;
  caption?: string;
  credit?: string;
  width: number;
  height: number;
}

export type BlogContent = string | BlogImage | BlogVideo;

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  /** ISO date string, e.g. "2026-08-06" */
  date: string;
  /** Each entry is one paragraph. Prefix with "## " for a subhead, "> " for an uppercase pull-quote, or ">> " for a mixed-case pull-quote. */
  content: BlogContent[];
  /** Optional hero photo for posts that ship with a specific image (use as-is, unaltered). */
  image?: string;
  imageAlt?: string;
  imageCaption?: string;
  imageCredit?: string;
  imageWidth?: number;
  imageHeight?: number;
  /** Optional SEO overrides — falls back to `title` / `excerpt` when omitted. */
  seoTitle?: string;
  metaDescription?: string;
  /** Optional topic tags for the post. */
  tags?: string[];
}

/**
 * BEHIND THE PRINT — post index
 *
 * To publish a new post: add a new object to the TOP of this array
 * (newest first). `slug` becomes the URL at /blog/<slug> — use lowercase
 * words separated by hyphens, no spaces or punctuation.
 */
export const BLOG_POSTS: BlogPost[] = [
  {
  slug: "the-card-i-didnt-know-i-needed",
  title: "The Card I Didn’t Know I Needed",
  excerpt:
    "A trip to the Bloomington Public Library for a simple library card became a reminder that learning, creativity, and community can meet us differently at every stage of life.",
  date: "2026-08-27",
  seoTitle: "The Card I Didn’t Know I Needed | Behind the Print",
  metaDescription:
    "A library card reconnects John with the stacks, creative possibility, community, and the challenge of learning how to explain decades of photography experience.",
  tags: [
    "Behind The Print",
    "Bloomington Public Library",
    "Photography",
    "Creative Growth",
    "Community",
    "Lifelong Learning",
  ],
  image: "/photos/the-card-i-didnt-know-i-needed.jpeg",
  imageAlt:
    "Illustrated John in his power wheelchair holding up a library card while talking with the established AI character inside a warmly lit library.",
  imageCaption:
    "Sometimes the thing you went in to get is only the beginning of what you find.",
  imageCredit: "AI-assisted artwork for Photography Fit 2 Print.",
  imageWidth: 1536,
  imageHeight: 864,
  content: [
    "I went to the Bloomington Public Library for a library card.",
    "At 59 years old.",
    "I remember thinking, What in the hell do I need a library card for? I don’t have a paper due. 😂",
    "Turns out, that was probably the wrong question.",
    "I’m no stranger to libraries. One of my first meaningful jobs was working at the Queens Public Library in New York while I was still in high school. I knew the stacks. I knew what libraries represented then.",
    "Books. Information. Research. A place to learn.",
    "What I hadn’t considered was what a library might mean to me now.",
    "Walking through the Bloomington Public Library, I started noticing things I wasn’t expecting. Creative spaces. Meeting rooms. Podcast resources. Technology. Places where people can gather, make things, learn something new, and share what they already know.",
    "The building had changed from the version of a library I had carried around in my head.",
    "Maybe I had changed too.",
    "These days I walk into places differently.",
    "I’m an artist and photographer. I notice light. I notice people. I notice spaces and possibilities. I’m usually wondering what could happen there, what could be photographed there, or what story might be hiding somewhere that everybody else just walked past.",
    "That curiosity is part of why my camera is rarely very far away.",
    "The funny thing is, I went into the library looking for access and walked out thinking about contribution.",
    "I learned about Bloomington Public Library’s Innovator-in-Residence program, where artists and other creatives can spend time sharing their craft with members of the community.",
    "Photography is included.",
    "Now, before anybody gets ahead of me, I haven’t signed myself up for another career. 😂",
    "I’m considering applying.",
    "And part of the reason has very little to do with whether I’m eventually selected.",
    "I want the exercise.",
    "Can I take decades of experience making photographs and explain what I actually know?",
    "Can I talk about why I make certain decisions?",
    "Can I explain light, composition, printing, storytelling and all the little choices that happen before somebody ever sees the finished photograph?",
    "Can I take something that has become almost instinctive through years of repetition and turn it back into understandable language for somebody who is just beginning?",
    "That interests me.",
    "Because knowing how to do something and knowing how to explain it are two different skills.",
    "Putting together an application also requires another kind of discipline. You have to gather your experience, decide what matters, explain your ideas clearly and make a case for why somebody should consider you.",
    "I need practice doing that too.",
    "Maybe I apply and get selected.",
    "Maybe I apply and don’t.",
    "Maybe I work through the process and decide the timing isn’t right.",
    "All three outcomes can still teach me something.",
    "There was a time when I probably would have seen an opportunity I liked and immediately started figuring out how to do everything associated with it.",
    "I’m learning to approach things differently now.",
    "Clarity.",
    "Responsibility.",
    "Self-awareness.",
    "Those things are required to make photographs well, run a business well, build relationships well and, apparently, decide whether you should volunteer to teach four photography classes at the public library.",
    "Who knew?",
    "There’s another part of this story that I like.",
    "I started working in a library when I was a teenager in Queens.",
    "Decades later, I walked into another library in Bloomington, Illinois, thinking I was simply getting a card.",
    "Instead, I found myself thinking again about learning, art, photography, community and what I might have to contribute.",
    "Turns out I wasn’t a stranger to the stacks.",
    "I just didn’t know what they might hold for me this time around.",
    "And that little plastic card?",
    "I think I needed it after all.",
    "> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
  ],
},
  {
    slug: "a-song-moved-me-to-tears",
    title: "A Song Moved Me to Tears",
    excerpt:
      "While Micro Spice performed “Die With a Smile,” one refrain brought nearly twenty years of love, loss, growth, and hard-earned clarity rushing back.",
    date: "2026-08-24",
    seoTitle: "A Song Moved Me to Tears | Behind the Print",
    metaDescription:
      "A live performance opens the door to love, emotional maturity, and the hope of facing life’s final moment beside someone who matters.",
    tags: [
      "Behind The Print",
      "Live Music",
      "Emotional Maturity",
      "Love",
      "Personal Reflection",
    ],
    image: "/photos/the-market-micro-spice.jpeg",
    imageAlt:
      "Micro Spice performs on the museum steps with vocals, saxophone and acoustic guitar as families move through the background.",
    imageCaption: "Micro Spice performing at the Downtown Bloomington Farmers Market.",
    imageCredit: "Photograph by John Guest, Photography Fit 2 Print.",
    imageWidth: 1638,
    imageHeight: 1093,
    content: [
      "Micro Spice was performing “Die With a Smile” when the words hit me like a ton of bricks.",
      "> “If the world was ending, I’d wanna be next to you.”",
      "That was enough.",
      "I sat there with emotions overflowing as every meaningful relationship in my life passed through my mind. I vacillated between the man I was before forty and the man sitting there now, nearly twenty years on the other side of it.",
      "That may be the biggest pivot in my life. I am still here, carrying nearly twenty more years of experience. I bear every bump and bruise. Every time I opened my heart. Every time I wasn’t emotionally mature enough to handle what came with it. Every time I loved somebody but didn’t yet know how to love them well.",
      "Age doesn’t erase any of that. If anything, clarity makes you look at it more honestly.",
      "The refrain reminded me that our time will come. None of us knows when. But I guess the hope for all of us is that, if it is God’s will, when the world ends for us, we’ll be holding on to that special someone.",
      "And we will, indeed, die with a smile.",
      "That is what art can do. A song can find the part of you that has been quietly carrying an entire lifetime and, without warning, open the door.",
      "> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
    ],
  },
  {
    slug: "the-market",
    title: "The Market",
    excerpt:
      "A photograph returned as a hug, a song broke something open, and a chance meeting between two artists completed the day.",
    date: "2026-08-23",
    seoTitle: "The Market: Photography, Sobriety and Human Connection",
    metaDescription:
      "At Bloomington’s Farmers Market, a returned portrait became a hug, music opened old wounds, and meeting another artist brought the day full circle.",
    tags: [
      "Behind The Print",
      "Intentional Photography",
      "Human Connection",
      "Sobriety",
      "Printed Photographs",
    ],
    image: "/photos/the-market-janie-goat.jpeg",
    imageAlt:
      "Janie Paslaski smiles while holding a small white goat at the Downtown Bloomington Farmers Market.",
    imageCaption: "Janie Paslaski of Middle Creek Farms holding a small white goat.",
    imageCredit: "Photograph by John Guest, Photography Fit 2 Print.",
    imageWidth: 1088,
    imageHeight: 725,
    content: [
      "Something felt different about my experience at the Downtown Bloomington Farmers Market yesterday morning.",
      "As soon as I rolled in, I ran into Janie Paslaski. Janie and her husband, Frank, own [Middle Creek Farms](https://middlecreek-farms.com/).",
      "I had photographed Janie holding a little goat. I could not help myself when I saw that moment. It presented itself to me, I accepted the opportunity, and I made the photograph.",
      "The Saturday before, I had given a physical print to Frank. Yesterday was the first time Janie had seen me since receiving it.",
      "She hugged me.",
      {
        type: "image",
        src: "/photos/the-market-janie-print.jpeg",
        alt: "A Canon printer holds a glossy portrait print of Janie Paslaski smiling while holding a white goat.",
        caption: "The physical print that returned to me as a hug.",
        credit: "Photograph and print by John Guest, Photography Fit 2 Print.",
        width: 2268,
        height: 4032,
      },
      "My day felt blessed right out of the gate.",
      "A photograph had left my hands, entered someone else’s life, and returned to me as gratitude. There was no sales pitch or transaction between us. Just a picture, a hug and a little humanity.",
      "> What that can do for the wounded parts of us all.",
      "My photography plan for the market was simple. I was shooting with intention and purpose. I wanted to make beautiful images, but I also wanted to make connections that were neither fake nor transactional.",
      "A real handshake. A pat on the back. A conversation that did not begin with somebody trying to sell something.",
      "Portraits that look and feel like the people standing in front of me.",
      "The interaction between subject and photographer felt warm. More importantly, it was warmly received. People did not seem to treat my camera like an intrusion. To me, it felt like a return to a time when we were not so far apart.",
      "I really miss those days.",
      "Everywhere I looked, small relationships were happening. People sat together and talked. A child rested against someone carrying him. A dog looked directly into my camera like he had been waiting all morning for me to arrive. A man walked through the market with a beautiful white bird perched on his shoulder.",
      {
        type: "image",
        src: "/photos/the-market-conversation.jpeg",
        alt: "Two people sit facing each other in conversation on a bench outside the McLean County Museum of History.",
        caption: "A real conversation in the middle of the market.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 1536,
        height: 1025,
      },
      {
        type: "image",
        src: "/photos/the-market-parent-child.jpeg",
        alt: "An adult carries a young child beneath the trees near the Downtown Bloomington Farmers Market.",
        caption: "Small relationships were happening everywhere I looked.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 1536,
        height: 1025,
      },
      {
        type: "image",
        src: "/photos/the-market-corgi.jpeg",
        alt: "A bright-eyed corgi looks toward the camera while riding in a carrier on a person’s back.",
        caption: "Some subjects know exactly where the camera is.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 2308,
        height: 1540,
      },
      {
        type: "image",
        src: "/photos/the-market-cockatoo.jpeg",
        alt: "A man wearing sunglasses and a Green Bay Packers cap carries a white cockatoo on his shoulder.",
        caption: "The market had no shortage of personality.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 2499,
        height: 1667,
      },
      "These were not props or pieces of content. They were people living their lives, and for a few seconds they allowed me to witness them.",
      "Then [Micro Spice](https://www.shireenbanigan.com/events/micro-spice-farmers-market-aug2026) began playing “Die With a Smile.”",
      {
        type: "image",
        src: "/photos/the-market-micro-spice.jpeg",
        alt: "Micro Spice performs on the museum steps with vocals, saxophone and acoustic guitar as families move through the background.",
        caption: "Micro Spice performing at the Downtown Bloomington Farmers Market.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 1638,
        height: 1093,
      },
      "I had heard the song before, but yesterday I listened to it.",
      "> There is a difference.",
      "The words reached someplace inside me that I was not prepared to visit in the middle of the Farmers Market. I rushed off to the side with tears streaming from underneath my Ray-Bans.",
      "I could not tell whether I was feeling the pain of a broken heart or confronting some brokenness inside me.",
      "Maybe it was both.",
      "Or maybe God’s plan was unfolding right there. Maybe the tears were not evidence that something was wrong. Maybe they were evidence of His presence.",
      "The music kept playing. People kept walking through the market. Life continued all around me while I sat off to the side, crying behind my sunglasses and feeling everything sobriety had returned to me.",
      "> Clarity is a gift. Nobody tells you how much it can hurt.",
      "I have always had the gift of gab. Anybody who knows me knows that. But listening is a different gift. Sobriety has given me the ability to hear words beyond the melody and appreciate meanings I may not have been available to receive before.",
      "The John Guest Experience had not always been fun.",
      "This version of me feels different. This version feels special because I was fully present for my own life.",
      "Then I met Brian.",
      "[Brian K. Simpson](https://brianksimpson.com/) is a talented pastel and charcoal artist. I told him that I see him around all the time. I often find myself watching for the opportunity to photograph him drawing someone interesting.",
      {
        type: "image",
        src: "/photos/the-market-brian-drawing.jpeg",
        alt: "Brian K. Simpson stands at his easel drawing a seated child near an Illinois Route 66 display in Downtown Bloomington.",
        caption: "Brian at work before we ever officially met.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 1536,
        height: 1025,
      },
      "He had appeared in my work before we ever officially met. That makes sense because Brian is as much a part of this art community as anyone.",
      "I have always believed that we are all artists. We simply use different tools and techniques.",
      "Brian works from life with pastel and charcoal. I work with light and a camera.",
      "> Yesterday, the portrait artist became my portrait.",
      {
        type: "image",
        src: "/photos/the-market-brian-portrait.jpeg",
        alt: "Artist Brian K. Simpson stands beside his easel outside the McLean County Museum of History wearing a straw hat and round glasses.",
        caption: "Yesterday, the portrait artist became my portrait.",
        credit: "Photograph by John Guest, Photography Fit 2 Print.",
        width: 1024,
        height: 1536,
      },
      "Meeting Brian and making his photograph completed my day.",
      "It began with one photograph returning to me as a hug. It ended with another photograph beginning.",
      "Somewhere in between, the music brought me to tears and reminded me that I was still here to experience all of it.",
      "> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
    ],
  },
  {
    slug: "moments-matter",
    title: "Moments Matter",
    excerpt:
      "Sometimes the camera is more than a tool. Sometimes it is comfort, continuity, and proof that a moment mattered enough to keep. This Behind the Print piece reflects on photography, self-awareness, and the power of turning images into heirloom prints.",
    date: "2026-08-19",
    seoTitle: "Moments Matter | Behind the Print | Photography Fit 2 Print",
    metaDescription:
      "A personal reflection on why photography matters, why prints matter, and how the moments we preserve become part of the way we live, remember, and endure.",
    tags: [
      "Behind The Print",
      "Personal Reflection",
      "Heirloom Prints",
      "Photography Philosophy",
      "Self-Awareness",
    ],
    image: "https://cdn.galaxy.ai/e1af2c0924bc49c1ad66a474d733f79f.webp",
    imageAlt:
      "Illustrated scene of John in his wheelchair holding his camera like a treasured possession while the AI character watches from a nearby screen in a warmly lit studio.",
    imageCaption: "A little humor, a lot of truth. Sometimes the camera really is the precious thing.",
    content: [
      "I love creating. So it’s probably worth noting that my camera is almost never out of reach.",
      "I feel like Linus carrying that blanket around everywhere. Hell, my Canon R5 Mark II is essentially my emotional support device.",
      "Every single time I’ve been hospitalized, my cameras were there with me. During times filled with uncertainty, they gave me something familiar to hold onto. I could look through my digital creations, edit photographs in Lightroom on my iPad, and stay connected to the thing I’ve loved for most of my life.",
      "Creating gave me somewhere to go mentally when physically I might have been stuck somewhere I didn’t want to be.",
      "> Eventually life removes the luxury of pretending certain realities are not there.",
      "Time will do that to you.",
      "At some point you have to face what is uncomfortable. You have to deal with what is real. I live with my realities, and I think one of my greatest superpowers is self-awareness. I know who I am. I know what I’ve been through. I know what I can do and what I can’t.",
      "So now that we got all that out of the way, let’s take some motherlovin’ pictures.",
      "Make the moment happen.",
      "That’s where photography keeps bringing me back.",
      "My job is to capture the moment, curate it, edit it with intention, and eventually produce something worthy of becoming an heirloom print.",
      "That last part matters to me more and more.",
      "A photograph sitting on a hard drive is still a photograph. I’m not going to pretend otherwise. But something changes when that image becomes physical.",
      "When it is printed.",
      "When it is framed.",
      "When it becomes part of the place where you live.",
      "Regardless of where you are economically, seeing your own work on display does something to you. It doesn’t have to be hanging in a museum or printed six feet wide. It just has to matter to you.",
      "As I move through my home, I’m surrounded by moments I was fortunate enough to witness and thoughtful enough to preserve.",
      "That is a strange and beautiful thing when you really think about it.",
      "I was the photographer who captured them.",
      "I was the person who decided they mattered.",
      "I was the one who curated them, worked on them, printed them, and gave them a physical life.",
      "But over time, something changes.",
      "> I stop being only the photographer.",
      "> I become the beneficiary.",
      "Now I get to walk past those moments. I get to admire them. See them. Touch them. Remember what was happening around them. Sometimes remember people. Sometimes remember places. Sometimes remember an entirely different version of myself.",
      "> A print lets you possess a moment without pretending you can possess time.",
      "Maybe that’s one of the reasons I keep carrying that camera around.",
      "I know time is going to keep moving whether I’m ready or not.",
      "But every once in a while, I get to catch something worth keeping.",
      "> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
    ],
  },
  {
    slug: "hey-what-are-you-looking-at",
    title: "Hey, What Are You Looking At?",
    excerpt:
      "We photographers can spend an extraordinary amount of time staring at photographs in ways nobody else ever will. This image from Miller Park Zoo reminded me that eventually you have to stop interrogating the pixels, back away from the screen and look at the photograph.",
    date: "2026-08-18",
    seoTitle: "Stop Pixel Peeping and Look at the Photograph | Photography Fit 2 Print",
    metaDescription:
      "An older photograph, an Olympus digital camera and one very patient tortoise offer a reminder that photography should be judged as a complete image, not merely at 300 percent on a monitor.",
    tags: [
      "Photography",
      "Printing",
      "Pixel Peeping",
      "Photography Craft",
      "Olympus",
      "Miller Park Zoo",
      "Fine Art Printing",
      "Digital Photography",
    ],
    image: "https://g.tlcdn.com/view/503f9f79e44945988013c6a38b03cf23.jpg",
    imageAlt:
      "Close low-angle photograph of a large tortoise at Miller Park Zoo beneath a deep blue sky, photographed by John Guest on August 2, 2020.",
    imageCaption: "Miller Park Zoo, August 2, 2020. Photographed with my trusted Olympus digital camera.",
    content: [
      "Hey, what are you looking at?",
      "You know no one really looks at pictures that way.",
      "Back up.",
      "Seriously. Back up from the screen.",
      "Nobody walks into somebody's house, sees a photograph hanging on the wall, gets six inches from the glass and starts examining the upper-left corner looking for noise.",
      "\"Well, John, at 300 percent I'm noticing a little softness around the tortoise's left eyelid.\"",
      "Man, get away from my picture.",
      "I took this photograph on August 2, 2020, at Miller Park Zoo with my trusted Olympus digital camera. At the time, I used the technology available to me and worked the image the best way I knew how.",
      "Technology has moved a long way since then. Cameras have changed. Software has changed. Noise reduction has changed. Sharpening has changed. AI has entered the room and apparently brought luggage.",
      "And somewhere along the way, photographers became extraordinarily talented at finding things wrong with photographs that almost nobody else would ever notice.",
      "We call it pixel peeping.",
      "There is a place for technical inspection. I believe deeply in craftsmanship. I care about resolution, sharpening, color, tonal relationships, file integrity and whether a photograph is properly prepared for its final destination.",
      "> Eventually you have to stop interrogating the pixels and look at the picture.",
      "Look at this guy.",
      "He was standing there looking like he had already survived several major geological events, completely unconcerned with my camera choice, dynamic range or whatever version of Photoshop I happened to be using.",
      "I was fortunate enough to be standing in front of him with a camera.",
      "That is where the photograph begins.",
      "The technology available to me in 2020 helped me create it. The technology available today might help me prepare it differently. Modern noise reduction may uncover detail more gracefully. Better enlargement methods may allow me to make a larger print. My own understanding of color, editing and printing has grown too.",
      "That is all useful.",
      "Use the tools.",
      "But don't let the tools convince you that the photograph didn't exist until the software approved it.",
      "That is where this starts drifting into familiar Photography Fit 2 Print territory.",
      "A photograph has another life waiting beyond the monitor.",
      "Print it.",
      "When a photograph becomes a physical object, the whole conversation changes. You are no longer staring at individual pixels. You are looking at texture, color, scale and light interacting with paper. You are standing at a normal viewing distance and experiencing the photograph as a complete image.",
      "Nobody pinches and zooms a print hanging on the wall.",
      "You approach it. You back away. Something catches your attention and pulls you closer. Maybe you notice the texture in the shell. Maybe it is the dirt beneath those massive feet. Maybe it is that rich blue sky sitting behind an animal that looks like he has absolutely nowhere he needs to be for the next hundred years.",
      "That relationship is different from anything happening on a phone.",
      "Older digital photographs can surprise you when you return to them. A file you dismissed years ago may have more life in it than you realized.",
      "> The photograph did not change.",
      "> You did.",
      "Your eye changed. Your editing changed. Your understanding of printing changed. The tools improved. Perhaps most importantly, you became better at understanding what the photograph actually needed.",
      "That does not mean every old image should be pushed through enough technology to make it look like it was photographed yesterday.",
      "Sometimes the job is simply to uncover what was already there.",
      "That distinction matters to me.",
      "Modern computational tools can reduce noise, refine detail, improve tonal relationships, prepare resolution for output and help us make better decisions about sharpening. Those tools can serve the photograph without becoming the photograph.",
      "Photography has always depended on technology. Film chemistry was technology. Darkroom dodging and burning were technology. Autofocus is technology. Digital sensors are technology. Lightroom is technology.",
      "The meaningful question is not whether technology touched the photograph.",
      "It is what we asked the technology to do.",
      "And eventually I want to stop talking about megapixels altogether.",
      "I want to know what happens when this tortoise gets off my monitor and onto a beautiful piece of paper.",
      "I want to see whether the detail in that shell becomes something you want to approach. I want to see those browns and oranges sitting against that blue sky without a backlit screen helping them along. I want to know whether the photograph can hold its own as an object.",
      "Can it make someone stop?",
      "Can it make someone smile?",
      "Can it return me to Miller Park Zoo on an August day in 2020 with an Olympus camera in my hands and enough curiosity to make the photograph?",
      "That is the test that interests me.",
      "Pixel peep when you need to. Inspect your files. Respect the craft. Use every good tool available to you.",
      "Then back up.",
      "Look at the photograph.",
      "And when the photograph is ready, finish the work.",
      "Have a photograph sitting on a hard drive that deserves another look? Photography Fit 2 Print can help you take it from digital file to finished photographic artwork.",
      "> We are Fit 2 Capture. We are Fit 2 Curate. We are Fit 2 Print.",
    ],
  },
  {
    slug: "hey-ai-you-alright",
    title: "Hey AI You Alright?",
    excerpt:
      "If something doesn't feel right, question it. Even if that means asking the AI if it's okay.",
    date: "2026-08-18",
    content: [
      "> If something doesn't feel right, question it. Even if that means asking the AI if it's okay.",
      "I'm not much for bragging.",
      "Most of the time, I'd rather let the work speak for itself.",
      "But every now and then, something happens behind the scenes that makes me sit back and think, \"Yeah, this is why we're building Photography Fit 2 Print this way.\"",
      "Lately, I've been working on a provenance system for our photography.",
      "That probably sounds more complicated than it needs to.",
      "In plain English, provenance is the history of the work.",
      "Who created it.",
      "What happened to it.",
      "What software touched it.",
      "Whether anything generative was added.",
      "Which version became the approved master.",
      "When it was printed.",
      "When it was published.",
      "If it was sold.",
      "Who owns a significant print.",
      "The goal is simple.",
      "If a photograph matters enough to make, print, sell, restore, preserve, or pass down, its history should matter too.",
      "What surprised me was how much the process itself started teaching me.",
      "I use AI heavily in the business. I make no secret of that.",
      "But I don't believe using AI means handing over responsibility.",
      "During one of our recent planning sessions, I was working with ChatGPT on the technical instructions for this provenance system. Something about the response felt off.",
      "So I asked:",
      "> \"Are you okay?\"",
      "That might sound funny considering I was talking to a machine.",
      "But what I was really saying was:",
      "> This doesn't feel like the standard of work we established.",
      "And I was right.",
      "We discovered that an instruction field had an 8,000-character limit. Some important governance language had been cut off.",
      "Nothing catastrophic happened.",
      "No photograph was touched.",
      "No data was lost.",
      "But the process wasn't right.",
      "So we corrected it.",
      "Then we did something more important.",
      "We turned the mistake into policy.",
      "We now maintain two different forms of documentation.",
      "The human version is written for me. It explains the reasoning, the history, the decisions, and why the controls exist.",
      "The machine version is stripped down. Raw. Precise. No unnecessary decoration. Just rules, permissions, priorities, boundaries, and instructions.",
      "And there is now another rule:",
      "> If a system has a hard limit, verify the finished instructions against that limit before declaring them ready.",
      "That little episode probably tells you more about Photography Fit 2 Print than a polished advertisement ever could.",
      "We are building systems that hold us accountable too.",
      "Not just the customer.",
      "Not just the software.",
      "Us.",
      "If we say your photograph matters, then the way we handle it should demonstrate that.",
      "If we say we care about preservation, we should be able to explain what we did.",
      "If we use advanced technology, we should also understand where its authority stops.",
      "And if something doesn't feel right, we should be willing to question it.",
      "Even if that means asking the AI if it's okay.",
      "Photography Fit 2 Print is becoming much more than a place where photographs get printed.",
      "We are building a way of working around photography that takes the image, its history, its physical life, and the people connected to it seriously.",
      "We are still building.",
      "Still learning.",
      "Still tightening the process.",
      "But I'm excited about where this is going.",
      "And if you have photographs, family history, artwork, restorations, or prints that deserve more than simply being dropped onto a hard drive and forgotten, keep an eye on what we're doing here.",
      "You may find that some of the things we're building for ourselves can help you protect what matters to you too.",
      "That's part of what happens Behind the Print.",
      "If you're interested in learning more about how Photography Fit 2 Print approaches photography, printing, restoration, preservation, and the story behind the image, visit phfit2print.com.",
      "> We are Fit 2 Capture. We are Fit 2 Curate. We are Fit 2 Print.",
    ],
  },
  {
    slug: "what-ai-is-teaching-me-about-my-business",
    title: "What AI Is Actually Teaching Me About My Business",
    excerpt:
      "A week of real AI use, not hype, taught me more about authorship, provenance and where the human line stays firm than any tutorial could.",
    date: "2026-08-18",
    content: [
      "I came across one of those random Facebook discussions asking business owners a few simple questions: Which AI platforms are you using? What did you actually use AI to accomplish in the last seven days? What did you try that didn't work?",
      "That last question got me.",
      "There is plenty of conversation about what AI can do. Depending on who you listen to, AI is either going to save every business in America or destroy civilization before lunch.",
      "I'm much more interested in what it is actually doing inside my business.",
      "Not theoretically. Not what somebody on YouTube says I should be doing. What did I actually use it for?",
      "## The Tools",
      "I use ChatGPT heavily. Claude has been involved particularly in some of the technical architecture surrounding the Photography Fit 2 Print provenance system.",
      "Adobe's AI-assisted tools are already woven into my photography workflow. I also use Evoto, Luminar Neo and ON1 tools for different parts of image processing. Magica has been another part of the broader environment I've been experimenting with.",
      "But simply listing platforms doesn't tell you very much.",
      "> Owning a hammer doesn't mean you built the house.",
      "The more interesting question is what all these tools are helping me accomplish.",
      "## What Did I Actually Do With AI?",
      "During the past week alone, I've used AI to work on Photography Fit 2 Print from several different directions.",
      "I've refined how I talk about the business. We've worked on messaging around printing, restoration, archival storage, NAS systems, provenance and something I believe strongly: photographs deserve a life beyond a screen.",
      "I've developed actual marketing material. Facebook posts. Threads posts. Website articles. Social media teasers. Ideas designed to bring people back to the Photography Fit 2 Print website and, hopefully, help them understand why printing, preservation and restoration matter.",
      "But I'm not just using AI to advertise the business.",
      "> I'm using it to help build the business.",
      "I've worked through equipment inventory, storage architecture, file migration, NAS reliability, digital-asset protection and operational documentation.",
      "That distinction matters to me. It is easy to reduce AI to \"write me a caption.\" There is nothing wrong with that. I do it too.",
      "But things became much more interesting when I stopped looking at AI simply as a writing machine and began using it as something closer to a collaborator, analyst and occasionally an intellectual sparring partner.",
      "## Then We Started Building Provenance",
      "Photography has entered an interesting period. A photograph can now be captured, computationally processed, retouched, altered, generated or some combination of all five.",
      "That creates a question I believe photographers and clients are increasingly going to care about: what exactly am I looking at?",
      "Photography Fit 2 Print has been developing a provenance system around that question. We have been working through an append-only ledger, XMP-first evidence gathering, cryptographic hashing, asset and master relationships, print records and rules surrounding generative content.",
      "Machines can gather evidence. Machines can propose classifications. But I have established an important boundary:",
      "> A machine should not silently make a material claim about the authorship or provenance of my artwork.",
      "There is still a human being responsible for the work. Me.",
      "That principle may eventually prove more important than the technology underneath it.",
      "## AI Has Also Been Helping Me Write",
      "I'm also working on a book. AI has helped me with continuity, structure, editing and occasionally figuring out what I am actually trying to say.",
      "But I don't want AI writing a book and attaching my name to it. There is a difference between helping me find the sentence and inventing the experience behind the sentence. Those experiences belong to me.",
      "Sometimes the most useful interaction I've had with AI ends with me saying: \"No. That isn't what I'm trying to say.\"",
      "That may sound like failure. It isn't. Sometimes having something reflected back at you makes your own position clearer.",
      "## I Use It in My Other Professional Life Too",
      "Photography is not my only professional discipline. I come from project controls and scheduling, so I've also used AI to examine employment opportunities, review my resume, evaluate how my experience aligns with positions, prepare for interviews and organize CAPM study material.",
      "That background has probably influenced how I'm approaching AI more than I initially realized. Project controls teaches you not to become impressed simply because something is moving. You want to know: What is the scope? What is the baseline? Who owns the decision? What changed? What is the impact? Where is the risk?",
      "AI deserves exactly the same questions.",
      "## Now Let's Talk About What Didn't Work",
      "There was a Photography Fit 2 Print campaign poster. It was terrible. Not mediocre. Terrible.",
      "I supplied finished photographs that I considered completed pieces of artwork. During the design process, those photographs effectively became raw material to be manipulated.",
      "I hated the result. We stopped. But something useful came out of it. I established a rule:",
      "> My photographs are finished artwork unless I explicitly authorize their alteration.",
      "That failure produced an operating standard. And that might be one of the most important things AI has done for my business.",
      "## Failure Can Reveal the Rule",
      "There have been smaller failures too. AI can over-polish my writing. Suddenly something I said sounds technically perfect but doesn't sound anything like me. My humor disappears. My cadence disappears. My lived experience gets replaced by something that sounds like it came from a conference-room presentation. No thank you.",
      "AI can also move toward execution too quickly. The provenance work has reinforced something I already understood from project controls:",
      "> Establish the rules before you automate the process.",
      "Authority first. Evidence second. Controls in place. Then automation.",
      "AI also has a tendency to give you fifteen good ideas simultaneously. That sounds wonderful until you realize you haven't fully understood idea number two and you're already saying yes to number eleven.",
      "Again, project controls. Scope it. Sequence it. Understand the dependencies. Then authorize the work.",
      "## Maybe We're Asking the Wrong Question",
      "Most conversations about artificial intelligence begin with: what can AI do? I'm beginning to think a more useful question for a business owner might be:",
      "> Where did AI fail, and what did that failure teach me about my business?",
      "The failed poster taught me something about artistic authorship. The provenance project taught me something about human authority. The NAS work taught me how easily technology can create a false sense of security. The writing taught me the difference between polish and voice.",
      "Those are not AI tricks. Those are governance lessons.",
      "## An AI Policy We Never Intended to Write",
      "One unintended consequence of all this is that Photography Fit 2 Print appears to be developing an AI policy without ever sitting down and declaring, \"Today we're going to write an AI policy.\"",
      "Instead, the policy is emerging from the work. Authorship matters. Provenance matters. Finished artwork should remain finished artwork. Generative content should be disclosed appropriately. Machines can gather evidence and make recommendations, but material decisions require human accountability. Technology should support the creative process rather than quietly taking ownership of it. Archival integrity matters. And just because something can be automated doesn't mean it should be automated.",
      "I didn't begin experimenting with AI expecting to arrive here. I was trying to become more efficient. Instead, the technology has forced me to become more specific about what Photography Fit 2 Print actually believes.",
      "And perhaps that is one of the most valuable things a new technology can do. It forces you to decide where you stand.",
      "> We are Fit 2 Capture. We are Fit 2 Curate. We are Fit 2 Print.",
    ],
  },
  {
    slug: "nas-storage-is-not-security",
    title: "NAS: Storage Is Not the Same as Security",
    excerpt:
      "Owning a Network Attached Storage box for two years taught me the hard way that redundancy, backup, and security are related concepts — but they are not the same thing.",
    date: "2026-08-16",
    content: [
      "First of all, this is not a retrospective on Nasty Nas from Queensbridge in my beloved Queens, New York. We are not about to spend the next ten minutes arguing about Jay-Z, Nas and The Notorious B.I.G. and who deserves to be called the best rapper alive.",
      "Although, for the record, I am apparently still close enough to relevance to know that this argument can ruin an otherwise perfectly good afternoon.",
      "I'm here to talk about a different NAS: Network Attached Storage.",
      "About two years ago, I invested in one.",
      "Silly me decided I could do the whole thing myself, armed with an unhealthy number of YouTube videos, a little confidence and just enough technical knowledge to become dangerous.",
      "At first, everything looked right.",
      "The drives were there. My files were there. I could access my photographs across the network. There were multiple disks spinning away inside a box that looked considerably more sophisticated than the external hard drives I had used for years.",
      "It felt safe.",
      "> That word matters.",
      "> Felt.",
      "Because one of the things I eventually learned is that storage, redundancy, backup, archival protection and security are related concepts, but they are not the same thing.",
      "## So What Is a NAS?",
      "At its simplest, Network Attached Storage is a dedicated storage system connected to your network rather than directly attached to one computer.",
      "Think of it as your own private file server.",
      "Instead of having photographs scattered across a laptop, desktop, external hard drives and whatever other device you forgot you copied them to, a NAS can provide a central location where authorized computers and devices can access those files.",
      "Depending upon how the system is configured, it can also provide drive redundancy, automatic backups, file synchronization, user permissions, remote access, versioning and other protections.",
      "That sounds wonderful.",
      "And it can be.",
      "But there is an important sentence hidden inside that paragraph:",
      "Depending upon how the system is configured.",
      "Owning a NAS does not automatically mean your files are backed up.",
      "Having multiple drives does not automatically mean your photographs are protected from deletion.",
      "RAID does not magically protect you from ransomware, fire, theft, accidental overwriting, corrupted files or a human being sitting at the keyboard making a terrible decision.",
      "I learned that there is an enormous difference between owning storage equipment and having a storage strategy.",
      "## Photographs Are Assets",
      "That distinction became increasingly important to me because Photography Fit 2 Print has grown beyond simply taking pictures.",
      "We capture.",
      "We curate.",
      "We edit.",
      "We print.",
      "We archive.",
      "And increasingly, we are thinking seriously about provenance — knowing where an image came from, what happened to it during the creative process, which version became the finished artwork and how that work should be preserved.",
      "Those files are not clutter sitting on a computer.",
      "They are business assets.",
      "More importantly, many of them are memories that cannot be recreated.",
      "A client portrait can be photographed again.",
      "Sometimes.",
      "A wedding cannot.",
      "A photograph of someone who has passed away cannot.",
      "That perfect expression, that family gathering, that performance, that trip, that moment when the light fell exactly where it needed to fall — those things do not care whether your hard drive failed.",
      "They are simply gone.",
      "That changed the way I began looking at storage.",
      "## The False Sense of Security",
      "I think this is where many photographers, artists and small businesses can get caught.",
      "We buy another hard drive and feel safer.",
      "Then we buy a NAS and feel even safer.",
      "There are four drives inside instead of one, so mathematically that has to mean we are four times safer, right?",
      "> Not necessarily.",
      "Redundancy can protect you from certain hardware failures. That is valuable.",
      "But redundancy is not necessarily backup.",
      "Backup is not necessarily disaster recovery.",
      "And having a backup sitting three feet away from the NAS may not help very much if something happens to the entire room.",
      "That was the part I had not fully understood when I began.",
      "YouTube had given me a collection of answers.",
      "What I did not yet have was an architecture.",
      "## This Time, We Built a System",
      "The NAS project eventually became something much larger than installing hard drives.",
      "We approached it as infrastructure.",
      "My photography archive had to be migrated. The network had to work reliably. The original files had to remain protected. We had to think about what could be automated, what required human confirmation and what information should follow an image throughout its life.",
      "And I am proud of what our team has accomplished.",
      "That word team is intentional.",
      "Some of the work involved hardware. Some involved software. Some involved artificial intelligence helping us investigate, document and test different approaches. And some required the one thing technology still cannot replace: a human being deciding what matters.",
      "We built the system around that distinction.",
      "Machines can gather evidence.",
      "Machines can check files.",
      "Machines can identify metadata.",
      "Machines can compare hashes and flag inconsistencies.",
      "But when something becomes part of the authoritative history of one of my photographs, I want a human decision involved.",
      "> Mine.",
      "Technology assists the process.",
      "It does not own the artwork.",
      "## The NAS Is Working",
      "Today, the files have been migrated.",
      "The NAS is operating across the network with very few issues.",
      "That sentence sounds almost boring.",
      "I love that.",
      "Infrastructure should eventually become boring.",
      "I don't want to wake up every morning excited because my storage array survived another night. I want to make photographs. I want to print. I want to work on Photography Fit 2 Print. I want the technology underneath those activities to quietly do its job.",
      "Getting there required learning something I wish I had understood two years ago:",
      "Buying a NAS is not the end of the storage conversation. It is the beginning of one.",
      "Before purchasing one, ask questions beyond how many terabytes it holds.",
      "What happens if a drive fails?",
      "What happens if two drives fail?",
      "What happens if you accidentally delete a folder?",
      "What happens if malware reaches the system?",
      "Where is the second copy?",
      "Is there an off-site copy?",
      "Can previous versions of a file be recovered?",
      "Who has permission to delete something?",
      "How will you know whether the backup actually worked?",
      "And perhaps the most uncomfortable question:",
      "> Have you ever tested whether you can get your files back?",
      "Because a backup you have never restored is partly an act of faith.",
      "## I Am Not Here to Sell You a NAS",
      "I am not telling you which box to buy.",
      "I am not telling you that everybody needs one.",
      "And I am certainly not pretending that two years of ownership suddenly made me a network-storage engineer.",
      "What I can share is the experience.",
      "I can tell you that I originally confused having more storage with having more protection.",
      "I can tell you that I underestimated how much planning should happen before the drives ever receive the first photograph.",
      "And I can tell you that once you begin treating photographs as long-term creative assets instead of disposable computer files, your entire attitude toward storage changes.",
      "That may lead you to a NAS.",
      "It may lead you somewhere else.",
      "But whatever solution you choose, understand what it protects you from — and just as importantly, what it does not.",
      "Because somewhere on one of those drives might be a photograph you don't yet realize will become priceless.",
      "> Protect it accordingly.",
      "And now that we have settled that…",
      "We can get back to the much easier question.",
      "> Nas, Jay-Z or Biggie?",
    ],
  },
  {
    slug: "the-photograph-that-time-will-choose",
    title: "The Photograph That Time Will Choose",
    excerpt:
      "No photographer presses the shutter with certainty — but every image deserves the craftsmanship worthy of an unknown future.",
    date: "2026-08-07",
    content: [
      "No photographer presses the shutter with the certainty that this will be the image future generations refuse to let fade.",
      "History never identifies its favorites in advance.",
      "The photograph destined to outlive us rarely announces its importance the day it is created.",
      "More often, it slips quietly into existence unnoticed. It is the unguarded laughter around the dinner table, a father's weathered hands resting on a child's shoulder, a mother's comforting embrace, the gap-toothed grin that disappears before anyone realizes how fleeting it was, or two grandparents sharing an ordinary afternoon that seemed too commonplace to matter.",
      "Yet time possesses an extraordinary gift.",
      "It elevates the familiar into something irreplaceable.",
      "The image overlooked today may become the one your children safeguard with quiet devotion. The framed portrait you pass without a second glance may someday inspire your grandchildren to ask, \"Who were they?\" A weathered album tucked away on a bookshelf may eventually become the final refuge for a smile, an expression, or a face that no longer exists anywhere else.",
      "None of us can foresee which frame will carry that burden.",
      "That uncertainty is precisely why every photograph deserves unwavering intention.",
      "Every exposure deserves patience.",
      "Every finished image deserves craftsmanship worthy of its unknown future.",
      "Not because each photograph belongs beneath gallery lights, but because any single frame may one day shoulder the weight of a family's story. Long after names have faded from memory, photographs often become the bridge that reconnects generations separated by decades.",
      "As photographers, we are never granted the luxury of deciding which images will matter half a century from now. That judgment belongs to time alone. Our calling is far simpler—and far more demanding.",
      "We create every photograph as though it could become someone's most treasured possession.",
      "That conviction is the heartbeat of Photography Fit 2 Print.",
      "It is more than a business name. It is a promise. A promise that every photograph leaving the studio has been crafted with the respect future memories deserve. Images intended not merely to exist on a screen, but to live on walls, rest in albums, pass through careful hands, and be rediscovered by people we will never meet.",
      "Because heirlooms are not born the moment the shutter closes.",
      "They earn that distinction one generation at a time—through remembrance, through preservation, and through the enduring affection of those who refuse to let the story disappear.",
    ],
  },
];
