import type { BlogPost } from "@/lib/blog-posts";

export const EXTRA_BLOG_POSTS: BlogPost[] = [
  {
    slug: "summers-end",
    title: "Summer’s End",
    excerpt:
      "At the end of another summer, joy, cultural continuity, and the finite nature of time sharpen one photographer’s responsibility to make family art that can outlive him.",
    date: "2026-09-03",
    seoTitle: "Summer’s End | Behind The Print",
    metaDescription:
      "John Guest reflects on summer, Black American cultural continuity, family photographs, and why making physical prints helps preserve the record for those who come after us.",
    tags: [
      "Behind The Print",
      "Summer",
      "Black American Culture",
      "Family Art",
      "Legacy",
      "Printed Photographs",
    ],
    image: "/photos/summers-end-hero.jpg",
    imageAlt:
      "John and AI study a freshly printed photograph as a late-summer community gathering winds down under string lights.",
    imageCaption: "The gathering ends. The photograph remains.",
    imageCredit:
      "Creative direction by John Guest. AI-assisted illustration using the approved John + AI character system.",
    imageWidth: 1672,
    imageHeight: 941,
    content: [
      "It’s that time of year again. Nearly the end of summer, and this one came and went like a fart in the wind.",
      "A summer of farmers markets and festivals. Festivals of Joy. Celebrations of Pride, humanity, peace, community. Under normal circumstances we’d probably be reaching for hoodies by now. Instead, it’s 97 degrees and we’re baking slow, like somebody left the grill on too long over Labor Day weekend. Somebody’s asking who made the potato salad. Somebody’s telling the DJ to turn down that bump-ta-dump and put some Luther on. Pour the Henny and suddenly everybody knows how to act right.",
      "That’s the sound of a summer worth remembering. And maybe that’s what has been sitting with me lately. Not just the photographs I made, but everything underneath them. The customs. The food. The music. The way people greet one another. The jokes that only make sense if you’ve been around long enough. The way a neighborhood sounds on a Saturday in August. The little rituals nobody thinks to call rituals because they’re simply part of life.",
      {
        type: "image",
        src: "/photos/summers-end-day-begins.jpg",
        alt: "John checks his camera beside AI at sunrise while a market and accessible van prepare for the day ahead.",
        caption: "Every remembered summer starts as an ordinary day.",
        credit:
          "Creative direction by John Guest. AI-assisted illustration using the approved John + AI character system.",
        width: 1672,
        height: 941,
      },
      "A few weeks ago I was photographing the Festival of Joy here in Bloomington. Camera up, doing the work I love, watching people celebrate themselves and their culture openly and unapologetically. Somewhere in the middle of all that joy, something unexpected showed up. Jealousy.",
      "Not the kind that makes you bitter. Not resentment. Just a quick pang that caught me off guard. I was looking at people celebrating customs that had a visible connection to somewhere. A culture with language, clothing, music, ritual, food, history and a line that could still be traced backward. People could point toward a place on the map and say, in one form or another, this is part of where we come from.",
      "And I felt the absence of that.",
      "That feeling forced me to think about something I already knew but don’t always walk around consciously carrying. Black Americans descended from slavery helped build this country. Our labor is embedded in its foundation, its wealth, its fields, roads, railroads, cities and industries. Generations of people worked, created, endured, survived and contributed while being denied something deeply human in the process: the ability to preserve an unbroken connection to who they had been before.",
      "Names were changed. Families were separated. Languages were interrupted. Records were incomplete, ignored, destroyed or never created in the first place. Specific connections to villages, nations, ethnic groups, traditions and bloodlines were often severed deliberately. That loss is difficult to measure because you’re trying to measure something that should have been passed down naturally.",
      "But here is the part I keep coming back to. We still created culture. We still created joy. We still created customs. We created music that changed the world. We created food traditions, family rituals, church traditions, neighborhood traditions, ways of speaking, celebrating, mourning, laughing and gathering that are unmistakably ours.",
      {
        type: "image",
        src: "/photos/summers-end-family-gathering.jpg",
        alt: "John laughs with AI, family, and creative collaborators during a summer cookout surrounded by photographs, music, and food.",
        caption: "Culture lives in the way we gather, laugh, make, and remember.",
        credit:
          "Creative direction by John Guest. AI-assisted illustration using the approved John + AI character system.",
        width: 1672,
        height: 941,
      },
      "We figured out how to turn a backyard into sacred ground for an afternoon. We figured out how to make a cookout feel like a family reunion even when half the people there weren’t technically related. We created traditions strong enough that you can walk into somebody else’s gathering hundreds of miles from home, hear the music, smell the food, catch the rhythm of the conversation and immediately recognize something familiar.",
      "So maybe the thing I was jealous of was not the existence of culture. We have plenty of that. Maybe it was continuity. The ability to say, with certainty, this came from here, and here is the line connecting me back to it. There is grief in recognizing that some of those lines were cut, but there is also something extraordinary in recognizing what people built afterward.",
      "Funny how I used to hear the old guys talk about getting older. They would say things like, “I might have ten good summers left,” or “I don’t know how many more summers I’ve got.” When you’re young, that sounds like old-man talk. Summer keeps coming. You assume there will always be another one.",
      "Now I’m 59.",
      "I’m not sitting around counting down my summers, but I understand what those men were saying in a way I couldn’t before. Time starts feeling less theoretical. I’m happy and grateful for the 59 summers I’ve already been fortunate enough to experience. Some were better than others. Some I probably wasted. Some I barely remember. Some changed the direction of my life. All of them belong to the story.",
      "That awareness has also changed the way I think about family photographs. I’m no longer satisfied with making pictures that live on a phone until somebody upgrades it, or on a hard drive nobody remembers the password to. If I make something meaningful of my family, my friends or my community, I want it to have a chance at surviving me.",
      "That is where Photography Fit 2 Print comes into this for me.",
      "Fit 2 Capture has always meant being present enough to recognize the moment. Fit 2 Curate means having enough judgment to decide which moments deserve more attention. But Fit 2 Print is where the photograph becomes something different. It becomes physical. Something your hand can touch. Something that can sit on a wall, live in an album, get passed from one person to another and eventually end up in the hands of somebody who wasn’t even alive when the shutter was pressed.",
      "That matters more to me at 59 than it probably would have at 29.",
      "I want to make family art.",
      "Not just pictures of family. Art made from the people, places, relationships and experiences that constitute a life. A photograph of your grandmother sitting at the picnic table might look ordinary today. Twenty years from now, everybody could be fighting over who gets the print. The portrait you almost didn’t bother making may eventually become the picture your children use to explain who somebody was.",
      "You rarely know which photograph will become important while you’re making it. That portrait of somebody laughing at a festival may someday be one of the few surviving records of what that community looked and felt like during this particular moment in time. The picture of cousins standing around the grill may become evidence of a whole generation that gathered there every Labor Day.",
      "That is part of what I am doing when I raise the camera. Yes, I’m looking for light, composition, expression and timing. I’m practicing a craft that I take seriously. But increasingly, I’m also thinking about permanence. I’m creating evidence that says we were here, we loved one another, we gathered, we celebrated, we got on each other’s nerves, we laughed, and we made something beautiful out of the time we had.",
      "Summer will end. Eventually somebody will finally put the hoodie on. The farmers markets will close for the season, the festivals will pack up, the grills will cool down and Luther will stop playing sometime around midnight. Another summer will become something we talk about in the past tense.",
      "The photograph can remain.",
      "Better yet, the print can remain.",
      "Maybe that is one of the quiet responsibilities I have accepted as a photographer and printmaker. I cannot restore every line history severed. I cannot recover every name that disappeared or every story that was never written down. But I can pay attention to the people standing in front of me now. I can make photographs with intention. I can print the ones that matter.",
      ">> Fit 2 Capture. | Fit 2 Curate. | Fit 2 Print.",
    ],
  },
  {
    slug: "i-had-to-live-with-this-one",
    title: "I Had to Live With This One",
    excerpt:
      "Some photographs are finished when the editing is done. Others keep calling you back. After creating this portrait of Alonna Gibson at ShutterFest 2024, I needed to know what would happen when the image left the screen and became a 13 × 19 inch fine-art print.",
    date: "2026-09-02",
    seoTitle: "I Had to Live With This One | Behind The Print",
    metaDescription:
      "John Guest reflects on printing Alonna Gibson’s ShutterFest portrait at 13 × 19 inches and why some photographs need to exist beyond a screen.",
    tags: [
      "Behind The Print",
      "Alonna Gibson",
      "ShutterFest 2024",
      "Portrait Photography",
      "Fine Art Printing",
      "Canon imagePROGRAF PRO-1000",
    ],
    image: "/photos/alonna-gibson-shutterfest-2024.jpg",
    imageAlt:
      "Portrait of Alonna Gibson surrounded by dark feathers, wearing a sparkling silver ensemble under cool blue and warm light.",
    imageCaption: "Alonna Gibson, photographed at ShutterFest 2024.",
    imageCredit: "Photograph and print by John Guest, Photography Fit 2 Print.",
    imageWidth: 1707,
    imageHeight: 2560,
    content: [
      "Alonna Gibson is enchanting in this photograph. I said something similar when I first shared the image on Facebook, but what I was feeling went further than simply thinking I had made a beautiful portrait. I kept coming back to it.",
      "The photograph was created at ShutterFest 2024 with my Canon EOS R and RF85mm F2 Macro IS STM. I photographed it at 85mm, 1/200 of a second, f/2.8 and ISO 200. Those are the technical facts of the capture, and they matter, but none of them really explain what happened afterward.",
      "What stayed with me was the way everything came together. Alonna’s expression has this quiet confidence to it. The feathers surround her without swallowing her. Cool blue light works its way through one side of the photograph while the warmer tones answer from the other. Then there is that ensemble. Every stone, every reflective surface and every little shimmer seems to find some piece of the light.",
      "I could appreciate all of that on a screen. I could zoom in, inspect the details and convince myself I had seen the photograph, but I had not seen it yet. I had already started imagining the print.",
      "That happens to me sometimes. An image crosses a line where I stop thinking about it as something that belongs on a monitor, a phone or a social media feed. I start wondering what it will do when it has physical dimensions. How will the colors behave on paper? Will those feathers still feel as deep? What happens to all of that sparkle when reflected light actually moves across the surface? Most importantly, what does the photograph feel like when I can stand in front of it instead of looking through a screen? I needed to know.",
      "So I printed Alonna on 13 × 19 inch Canon Fine Art Smooth paper using my Canon imagePROGRAF PRO-1000, and there it was. Nothing about the photograph had changed, yet my relationship with it had. The pixels were the same. Alonna was the same. My decisions during the capture and editing were already made. What changed was how I experienced the image.",
      "A physical print occupies space with you. I could move closer and look at the small reflections scattered across her wardrobe, then back away and let the feathers and color become the composition again. The photograph responded differently as the room light changed. Instead of reaching for a screen and opening a file, I could simply look over and there she was.",
      "I even recorded video of the print because I wanted to capture some of what I was experiencing.",
      {
        type: "video",
        src: "/videos/alonna-print-pro1000.mov",
        poster: "/photos/alonna-print-pro1000-poster.jpg",
        title: "Alonna Gibson’s portrait emerging from the Canon imagePROGRAF PRO-1000",
        caption: "The 13 × 19 inch print emerging from the Canon imagePROGRAF PRO-1000.",
        credit: "Video by John Guest, Photography Fit 2 Print.",
        width: 540,
        height: 960,
      },
      "There is some irony in making a digital video to explain why the digital photograph was not enough, but maybe that makes the point better. I was not trying to prove that one medium was superior to another. I was documenting the moment when an image I had worked on became a physical piece of photographic artwork. I wanted to live with the print, and that phrase has stayed with me.",
      "We make an incredible number of photographs now, and most of them are consumed very quickly. We look, swipe, maybe zoom, perhaps tap a heart, and continue moving. Even photographs that matter to us can eventually disappear underneath thousands of other photographs in a camera roll or on a hard drive.",
      "A print asks something different of us. Somebody has to decide that this particular photograph deserves another step. It deserves the paper. It deserves the ink. It deserves the time spent looking at the finished result and deciding whether what came out of the printer represents what you intended when you first created the image.",
      "Printing also exposes you. A screen can be forgiving in ways paper is not. Color, tonal relationships, sharpening, texture and small editing decisions become part of a finished object. My PRO-1000 does not care how much I like the photograph. The print tells me what is actually there.",
      "That is one reason printmaking remains important to my photography. Printing is not merely a delivery option sitting at the end of the process. It is another stage of the craft. Capture gives me the raw material. Curation determines what deserves my attention. Editing helps me bring the photograph toward the image I imagined. Printing forces me to finish the thought, and sometimes a photograph surprises me once it gets there.",
      "When I first shared Alonna’s portrait, I wrote that every sparkling shimmer of her ensemble could brighten the mood and day of that special someone. Looking back at those words, I realize I was already thinking about the photograph as something more than a Facebook post. I was imagining the print before I printed it. Now I have lived with it, and I like it even more.",
      ">> Fit 2 Capture. | Fit 2 Curate. | Fit 2 Print.",
    ],
  },
  {
    slug: "an-extraordinary-collection-of-beginnings",
    title: "An Extraordinary Collection of Beginnings",
    excerpt:
      "I asked AI to stop helping me make things and look instead at the record of what I had already been doing. What emerged was an uncomfortable question about ideas, concentration, unfinished work, and what happens when curiosity is allowed to interrupt everything.",
    date: "2026-08-31",
    seoTitle: "An Extraordinary Collection of Beginnings | Behind the Print",
    metaDescription:
      "John Guest examines a pattern hidden inside years of projects, photography and ideas, then begins a 30-day experiment to find out what changes when fewer things receive more attention.",
    tags: [
      "Behind The Print",
      "Creative Process",
      "Photography",
      "Focus",
      "Personal Reflection",
      "Bloomington Public Library",
    ],
    image: "/photos/John-and-AI-Beginnings-Store-Hero-web.JPEG",
    imageAlt:
      "Illustrated John in his power wheelchair holding a seedling package while the AI character pushes a cart overflowing with photographs, notebooks, cameras and unfinished ideas beneath a Beginnings sign.",
    imageCaption: "Apparently, we’re buying all the beginnings.",
    imageCredit: "AI-assisted artwork for Photography Fit 2 Print.",
    imageWidth: 1672,
    imageHeight: 941,
    content: [
      "I've accumulated enough conversations with AI that something interesting has started to happen. There is a record now. Not just of the questions I've asked, but of projects I've started, photographs I've worked on, things I've finished, things I've changed my mind about and ideas that were apparently important enough for me to spend three hours discussing before another idea showed up.",
      "So I decided to use that record differently.",
      "Instead of asking AI to help me make something, I asked it to look at what I had already been doing and tell me what it saw.",
      "I wasn't particularly interested in compliments. I wanted the patterns.",
      "There was plenty of material. Photography Fit 2 Print alone has generated conversations about portraits, community photography, restoration, printing, competitions, the website, business systems and the provenance work I've been developing to document what happens to my photographs. Then there's Behind the Print, my interest in teaching, the Bloomington Public Library and its Innovator-in-Residence program, and some serious thinking I've started doing about legacy.",
      "On paper, that's a lot.",
      "Maybe too much.",
      "That was one of the first things the analysis exposed.",
      "## Busy Is Not the Same as Focused",
      "I have spent a good portion of my professional life in project controls. Give me a complicated problem and my instinct is to start figuring out how the pieces relate. What happens first? What depends on what? Where are the risks? What needs to be controlled?",
      "Apparently I brought that guy with me into photography.",
      "It has been useful. Photography Fit 2 Print isn't being built entirely on improvisation. I'm thinking about the photographs, but I'm also thinking about what happens to them afterward. How they're edited. How they're printed. How they're stored. How their history is preserved. How somebody other than me might eventually understand what they're looking at.",
      "The problem is that I can do the same thing with an idea.",
      "An idea shows up and pretty soon I can see what it could become. Then I see what would be required to make it work properly. That reveals another possibility. Before long, something that started as a simple thought has architecture.",
      "The strange part is that this doesn't feel like procrastination because I'm not sitting around doing nothing. I'm usually working pretty damn hard.",
      "That may be exactly why it took me a while to recognize the problem.",
      "There is a difference between being busy and concentrating effort long enough for something to compound.",
      "I have plenty of evidence of the first one.",
      "I want more evidence of the second.",
      "## I Thought I Had Several Different Interests",
      "Another part of the analysis surprised me.",
      "Photography, printing, restoration, writing, teaching, archiving, provenance and legacy planning can look like separate pursuits. I've occasionally wondered whether I'm trying to make Photography Fit 2 Print carry too many ideas.",
      "Maybe I am. That question isn't settled.",
      "But when I stopped looking at the labels and looked at what I actually do, I noticed something connecting a lot of them.",
      "I care about what survives.",
      "That shows up very literally in restoration. An old photograph may be damaged, noisy, faded or technically limited, but the reason somebody cares about it usually has very little to do with pixels. Somebody they love is standing in that picture.",
      "It shows up in printing too. I have never been particularly interested in photography ending as another image somebody scrolls past. There is something different about making an object that can live on somebody's wall.",
      "The provenance work takes the same instinct into a much more technical direction. If a photograph matters, I want to know where it came from, what happened to it and what was changed. That became even more important to me as generative AI started complicating what a photograph can mean.",
      "Behind the Print may be another version of the same thing. I'm not only interested in showing the finished photograph. Increasingly, I want to preserve some record of what was happening around it.",
      "That doesn't mean I've discovered some grand unified theory of myself. I'm suspicious of conclusions that neat.",
      "But there is enough evidence for me to keep following the thread.",
      "## Then the Analysis Got Uncomfortable",
      "One observation bothered me because I recognized it immediately.",
      "Starting something can be rewarding.",
      "There is possibility in a beginning. Nothing has failed yet. Nothing has disappointed you. The thing in your head can still become everything you imagine it might be.",
      "Finishing changes the relationship.",
      "Eventually the photograph has to be shown. The application has to be submitted. The article has to be published. The service has to encounter an actual customer. Somebody besides me gets a vote.",
      "I don't think I'm afraid of criticism. I've had enough life and enough professional experience to survive somebody not liking my work.",
      "But I do think I enjoy possibility, and I may enjoy it enough that I sometimes give the next possibility attention that belongs to something already underway.",
      "That's a different problem.",
      "And if I'm right about it, another planning exercise isn't going to fix it.",
      "## What Repetition Can Do",
      "This is where photography gives me a useful way of thinking about the problem.",
      "I can go downtown one Saturday and make some photographs. Maybe I get something beautiful. Maybe I meet somebody interesting. That's worthwhile on its own.",
      "But what happens if I keep going?",
      "What happens if I photograph the Bloomington Farmers Market for five years?",
      "People change. Vendors change. Downtown changes. Buildings change. Somebody I photographed once becomes somebody I've photographed twenty times. A collection starts developing relationships that no individual photograph could contain.",
      "Time starts contributing to the work.",
      "I can't manufacture that in Lightroom.",
      "The same thing applies elsewhere. One restoration is one restoration. One essay is one essay. One print is one print. Enough deliberate work, finished consistently over time, starts becoming a body of work.",
      "That's where I think I've been leaving something on the table.",
      "Not because I haven't been working.",
      "Because accumulation requires staying with things after the excitement of discovering them has worn off.",
      "## A Thirty-Day Experiment",
      "The timing of all this is interesting because I have something sitting directly in front of me.",
      "I've been considering applying for the Bloomington Public Library's Innovator-in-Residence program.",
      "The ideas are already developing. I've been thinking about teaching photography through observation, light, composition, connection and dignity. I've been thinking about what it means to teach somebody to see rather than simply teach them how to operate a camera.",
      "Normally, I could probably turn that into six additional projects before lunch.",
      "I'm going to try something different.",
      "For the next 30 days, the application gets finished.",
      "That doesn't mean Photography Fit 2 Print shuts down. I'm still going to photograph. Existing work still exists. Life still gets a vote.",
      "It means a new idea doesn't automatically earn the right to interrupt something I've already decided matters.",
      "I can write the idea down.",
      "It can wait.",
      "That sounds ridiculously simple when I read it back.",
      "Maybe it is.",
      "## I Want the Evidence",
      "One thing I don't want to do is write the ending of this story before I've lived it.",
      "I don't know whether concentrating my attention this way will produce dramatically different results. I don't know whether the library will select me. I don't know whether I'll discover that some projects I've been protecting should actually be abandoned.",
      "That's the useful part.",
      "Thirty days from now there will be data.",
      "Did I submit the application?",
      "What else did I finish?",
      "What did I choose not to start?",
      "Did anything important suffer because I narrowed my attention?",
      "Did I feel constrained, or did I finally give myself enough room to work?",
      "Those answers interest me more than another theory about productivity.",
      "I'm 59. I don't say that because I think the clock is about to run out. I say it because I've lived long enough to understand that time is an actual resource.",
      "I've spent a career managing resources.",
      "Maybe it's time I became a little more disciplined about this one.",
      "There are still a ridiculous number of things I want to photograph, make, learn, write and experience. I'm not interested in becoming less curious to make myself more efficient.",
      "I'm interested in finding out what happens when curiosity stops getting automatic authority over concentration.",
      "So that's the experiment.",
      "I'll keep the ideas.",
      "I'm just going to make them wait their turn.",
      "And in 30 days, instead of asking what I think about it, I'll look at what I finished.",
      "Photography Fit 2 Print",
      "Fit to Capture | Fit to Curate | Fit to Print",
    ],
  },
];
