export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  /** ISO date string, e.g. "2026-08-06" */
  date: string;
  /** Each entry is one paragraph. Prefix with "## " for a subhead, "> " for a pull-quote. */
  content: string[];
}

/**
 * BEHIND THE PRINT — post index
 *
 * To publish a new post: add a new object to the TOP of this array
 * (newest first). `slug` becomes the URL at /blog/<slug> — use lowercase
 * words separated by hyphens, no spaces or punctuation.
 */
export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "nas-storage-is-not-security",
    title: "NAS: Storage Is Not the Same as Security",
    excerpt:
      "Owning a Network Attached Storage box for two years taught me the hard way that redundancy, backup, and security are related concepts — but they are not the same thing.",
    date: "2026-08-16",
    content: [
      "First of all, this is not a retrospective on Nasty Nas from Queensbridge in my beloved Queens, New York. We are not about to spend the next ten minutes arguing about Jay-Z, Nas and The Notorious B.I.G. and who deserves to be called the best rapper alive.",
      "Although, for the record, I am apparently still close enough to relevance to know that this argument can ruin an otherwise perfectly good afternoon.",
      "I'm here to talk about a different NAS: Network Attached Storage.",
      "About two years ago, I invested in one.",
      "Silly me decided I could do the whole thing myself, armed with an unhealthy number of YouTube videos, a little confidence and just enough technical knowledge to become dangerous.",
      "At first, everything looked right.",
      "The drives were there. My files were there. I could access my photographs across the network. There were multiple disks spinning away inside a box that looked considerably more sophisticated than the external hard drives I had used for years.",
      "It felt safe.",
      "> That word matters.",
      "> Felt.",
      "Because one of the things I eventually learned is that storage, redundancy, backup, archival protection and security are related concepts, but they are not the same thing.",
      "## So What Is a NAS?",
      "At its simplest, Network Attached Storage is a dedicated storage system connected to your network rather than directly attached to one computer.",
      "Think of it as your own private file server.",
      "Instead of having photographs scattered across a laptop, desktop, external hard drives and whatever other device you forgot you copied them to, a NAS can provide a central location where authorized computers and devices can access those files.",
      "Depending upon how the system is configured, it can also provide drive redundancy, automatic backups, file synchronization, user permissions, remote access, versioning and other protections.",
      "That sounds wonderful.",
      "And it can be.",
      "But there is an important sentence hidden inside that paragraph:",
      "Depending upon how the system is configured.",
      "Owning a NAS does not automatically mean your files are backed up.",
      "Having multiple drives does not automatically mean your photographs are protected from deletion.",
      "RAID does not magically protect you from ransomware, fire, theft, accidental overwriting, corrupted files or a human being sitting at the keyboard making a terrible decision.",
      "I learned that there is an enormous difference between owning storage equipment and having a storage strategy.",
      "## Photographs Are Assets",
      "That distinction became increasingly important to me because Photography Fit 2 Print has grown beyond simply taking pictures.",
      "We capture.",
      "We curate.",
      "We edit.",
      "We print.",
      "We archive.",
      "And increasingly, we are thinking seriously about provenance — knowing where an image came from, what happened to it during the creative process, which version became the finished artwork and how that work should be preserved.",
      "Those files are not clutter sitting on a computer.",
      "They are business assets.",
      "More importantly, many of them are memories that cannot be recreated.",
      "A client portrait can be photographed again.",
      "Sometimes.",
      "A wedding cannot.",
      "A photograph of someone who has passed away cannot.",
      "That perfect expression, that family gathering, that performance, that trip, that moment when the light fell exactly where it needed to fall — those things do not care whether your hard drive failed.",
      "They are simply gone.",
      "That changed the way I began looking at storage.",
      "## The False Sense of Security",
      "I think this is where many photographers, artists and small businesses can get caught.",
      "We buy another hard drive and feel safer.",
      "Then we buy a NAS and feel even safer.",
      "There are four drives inside instead of one, so mathematically that has to mean we are four times safer, right?",
      "> Not necessarily.",
      "Redundancy can protect you from certain hardware failures. That is valuable.",
      "But redundancy is not necessarily backup.",
      "Backup is not necessarily disaster recovery.",
      "And having a backup sitting three feet away from the NAS may not help very much if something happens to the entire room.",
      "That was the part I had not fully understood when I began.",
      "YouTube had given me a collection of answers.",
      "What I did not yet have was an architecture.",
      "## This Time, We Built a System",
      "The NAS project eventually became something much larger than installing hard drives.",
      "We approached it as infrastructure.",
      "My photography archive had to be migrated. The network had to work reliably. The original files had to remain protected. We had to think about what could be automated, what required human confirmation and what information should follow an image throughout its life.",
      "And I am proud of what our team has accomplished.",
      "That word team is intentional.",
      "Some of the work involved hardware. Some involved software. Some involved artificial intelligence helping us investigate, document and test different approaches. And some required the one thing technology still cannot replace: a human being deciding what matters.",
      "We built the system around that distinction.",
      "Machines can gather evidence.",
      "Machines can check files.",
      "Machines can identify metadata.",
      "Machines can compare hashes and flag inconsistencies.",
      "But when something becomes part of the authoritative history of one of my photographs, I want a human decision involved.",
      "> Mine.",
      "Technology assists the process.",
      "It does not own the artwork.",
      "## The NAS Is Working",
      "Today, the files have been migrated.",
      "The NAS is operating across the network with very few issues.",
      "That sentence sounds almost boring.",
      "I love that.",
      "Infrastructure should eventually become boring.",
      "I don't want to wake up every morning excited because my storage array survived another night. I want to make photographs. I want to print. I want to work on Photography Fit 2 Print. I want the technology underneath those activities to quietly do its job.",
      "Getting there required learning something I wish I had understood two years ago:",
      "Buying a NAS is not the end of the storage conversation. It is the beginning of one.",
      "Before purchasing one, ask questions beyond how many terabytes it holds.",
      "What happens if a drive fails?",
      "What happens if two drives fail?",
      "What happens if you accidentally delete a folder?",
      "What happens if malware reaches the system?",
      "Where is the second copy?",
      "Is there an off-site copy?",
      "Can previous versions of a file be recovered?",
      "Who has permission to delete something?",
      "How will you know whether the backup actually worked?",
      "And perhaps the most uncomfortable question:",
      "> Have you ever tested whether you can get your files back?",
      "Because a backup you have never restored is partly an act of faith.",
      "## I Am Not Here to Sell You a NAS",
      "I am not telling you which box to buy.",
      "I am not telling you that everybody needs one.",
      "And I am certainly not pretending that two years of ownership suddenly made me a network-storage engineer.",
      "What I can share is the experience.",
      "I can tell you that I originally confused having more storage with having more protection.",
      "I can tell you that I underestimated how much planning should happen before the drives ever receive the first photograph.",
      "And I can tell you that once you begin treating photographs as long-term creative assets instead of disposable computer files, your entire attitude toward storage changes.",
      "That may lead you to a NAS.",
      "It may lead you somewhere else.",
      "But whatever solution you choose, understand what it protects you from — and just as importantly, what it does not.",
      "Because somewhere on one of those drives might be a photograph you don't yet realize will become priceless.",
      "> Protect it accordingly.",
      "And now that we have settled that…",
      "We can get back to the much easier question.",
      "> Nas, Jay-Z or Biggie?",
    ],
  },
  {
    slug: "the-photograph-that-time-will-choose",
    title: "The Photograph That Time Will Choose",
    excerpt:
      "No photographer presses the shutter with certainty — but every image deserves the craftsmanship worthy of an unknown future.",
    date: "2026-08-07",
    content: [
      "No photographer presses the shutter with the certainty that this will be the image future generations refuse to let fade.",
      "History never identifies its favorites in advance.",
      "The photograph destined to outlive us rarely announces its importance the day it is created.",
      "More often, it slips quietly into existence unnoticed. It is the unguarded laughter around the dinner table, a father’s weathered hands resting on a child’s shoulder, a mother’s comforting embrace, the gap-toothed grin that disappears before anyone realizes how fleeting it was, or two grandparents sharing an ordinary afternoon that seemed too commonplace to matter.",
      "Yet time possesses an extraordinary gift.",
      "It elevates the familiar into something irreplaceable.",
      "The image overlooked today may become the one your children safeguard with quiet devotion. The framed portrait you pass without a second glance may someday inspire your grandchildren to ask, “Who were they?” A weathered album tucked away on a bookshelf may eventually become the final refuge for a smile, an expression, or a face that no longer exists anywhere else.",
      "None of us can foresee which frame will carry that burden.",
      "That uncertainty is precisely why every photograph deserves unwavering intention.",
      "Every exposure deserves patience.",
      "Every finished image deserves craftsmanship worthy of its unknown future.",
      "Not because each photograph belongs beneath gallery lights, but because any single frame may one day shoulder the weight of a family’s story. Long after names have faded from memory, photographs often become the bridge that reconnects generations separated by decades.",
      "As photographers, we are never granted the luxury of deciding which images will matter half a century from now. That judgment belongs to time alone. Our calling is far simpler—and far more demanding.",
      "We create every photograph as though it could become someone’s most treasured possession.",
      "That conviction is the heartbeat of Photography Fit 2 Print.",
      "It is more than a business name. It is a promise. A promise that every photograph leaving the studio has been crafted with the respect future memories deserve. Images intended not merely to exist on a screen, but to live on walls, rest in albums, pass through careful hands, and be rediscovered by people we will never meet.",
      "Because heirlooms are not born the moment the shutter closes.",
      "They earn that distinction one generation at a time—through remembrance, through preservation, and through the enduring affection of those who refuse to let the story disappear.",
    ],
  },
];
