export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  /** ISO date string, e.g. "2026-08-06" */
  date: string;
  /** Each entry is one paragraph. Prefix with "## " for a subhead, "> " for a pull-quote. */
  content: string[];
}

/**
 * BEHIND THE PRINT — post index
 *
 * To publish a new post: add a new object to the TOP of this array
 * (newest first). `slug` becomes the URL at /blog/<slug> — use lowercase
 * words separated by hyphens, no spaces or punctuation.
 */
export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "hey-ai-you-alright",
    title: "Hey AI You Alright?",
    excerpt:
      "If something doesn't feel right, question it. Even if that means asking the AI if it's okay.",
    date: "2026-08-18",
    content: [
      "> If something doesn't feel right, question it. Even if that means asking the AI if it's okay.",
      "I'm not much for bragging.",
      "Most of the time, I'd rather let the work speak for itself.",
      "But every now and then, something happens behind the scenes that makes me sit back and think, \"Yeah, this is why we're building Photography Fit 2 Print this way.\"",
      "Lately, I've been working on a provenance system for our photography.",
      "That probably sounds more complicated than it needs to.",
      "In plain English, provenance is the history of the work.",
      "Who created it.",
      "What happened to it.",
      "What software touched it.",
      "Whether anything generative was added.",
      "Which version became the approved master.",
      "When it was printed.",
      "When it was published.",
      "If it was sold.",
      "Who owns a significant print.",
      "The goal is simple.",
      "If a photograph matters enough to make, print, sell, restore, preserve, or pass down, its history should matter too.",
      "What surprised me was how much the process itself started teaching me.",
      "I use AI heavily in the business. I make no secret of that.",
      "But I don't believe using AI means handing over responsibility.",
      "During one of our recent planning sessions, I was working with ChatGPT on the technical instructions for this provenance system. Something about the response felt off.",
      "So I asked:",
      "> \"Are you okay?\"",
      "That might sound funny considering I was talking to a machine.",
      "But what I was really saying was:",
      "> This doesn't feel like the standard of work we established.",
      "And I was right.",
      "We discovered that an instruction field had an 8,000-character limit. Some important governance language had been cut off.",
      "Nothing catastrophic happened.",
      "No photograph was touched.",
      "No data was lost.",
      "But the process wasn't right.",
      "So we corrected it.",
      "Then we did something more important.",
      "We turned the mistake into policy.",
      "We now maintain two different forms of documentation.",
      "The human version is written for me. It explains the reasoning, the history, the decisions, and why the controls exist.",
      "The machine version is stripped down. Raw. Precise. No unnecessary decoration. Just rules, permissions, priorities, boundaries, and instructions.",
      "And there is now another rule:",
      "> If a system has a hard limit, verify the finished instructions against that limit before declaring them ready.",
      "That little episode probably tells you more about Photography Fit 2 Print than a polished advertisement ever could.",
      "We are building systems that hold us accountable too.",
      "Not just the customer.",
      "Not just the software.",
      "Us.",
      "If we say your photograph matters, then the way we handle it should demonstrate that.",
      "If we say we care about preservation, we should be able to explain what we did.",
      "If we use advanced technology, we should also understand where its authority stops.",
      "And if something doesn't feel right, we should be willing to question it.",
      "Even if that means asking the AI if it's okay.",
      "Photography Fit 2 Print is becoming much more than a place where photographs get printed.",
      "We are building a way of working around photography that takes the image, its history, its physical life, and the people connected to it seriously.",
      "We are still building.",
      "Still learning.",
      "Still tightening the process.",
      "But I'm excited about where this is going.",
      "And if you have photographs, family history, artwork, restorations, or prints that deserve more than simply being dropped onto a hard drive and forgotten, keep an eye on what we're doing here.",
      "You may find that some of the things we're building for ourselves can help you protect what matters to you too.",
      "That's part of what happens Behind the Print.",
      "If you're interested in learning more about how Photography Fit 2 Print approaches photography, printing, restoration, preservation, and the story behind the image, visit phfit2print.com.",
      "> We are Fit 2 Capture. We are Fit 2 Curate. We are Fit 2 Print.",
    ],
  },
  {
    slug: "what-ai-is-teaching-me-about-my-business",
    title: "What AI Is Actually Teaching Me About My Business",
    excerpt:
      "A week of real AI use, not hype, taught me more about authorship, provenance and where the human line stays firm than any tutorial could.",
    date: "2026-08-18",
    content: [
      "I came across one of those random Facebook discussions asking business owners a few simple questions: Which AI platforms are you using? What did you actually use AI to accomplish in the last seven days? What did you try that didn't work?",
      "That last question got me.",
      "There is plenty of conversation about what AI can do. Depending on who you listen to, AI is either going to save every business in America or destroy civilization before lunch.",
      "I'm much more interested in what it is actually doing inside my business.",
      "Not theoretically. Not what somebody on YouTube says I should be doing. What did I actually use it for?",
      "## The Tools",
      "I use ChatGPT heavily. Claude has been involved particularly in some of the technical architecture surrounding the Photography Fit 2 Print provenance system.",
      "Adobe's AI-assisted tools are already woven into my photography workflow. I also use Evoto, Luminar Neo and ON1 tools for different parts of image processing. Magica has been another part of the broader environment I've been experimenting with.",
      "But simply listing platforms doesn't tell you very much.",
      "> Owning a hammer doesn't mean you built the house.",
      "The more interesting question is what all these tools are helping me accomplish.",
      "## What Did I Actually Do With AI?",
      "During the past week alone, I've used AI to work on Photography Fit 2 Print from several different directions.",
      "I've refined how I talk about the business. We've worked on messaging around printing, restoration, archival storage, NAS systems, provenance and something I believe strongly: photographs deserve a life beyond a screen.",
      "I've developed actual marketing material. Facebook posts. Threads posts. Website articles. Social media teasers. Ideas designed to bring people back to the Photography Fit 2 Print website and, hopefully, help them understand why printing, preservation and restoration matter.",
      "But I'm not just using AI to advertise the business.",
      "> I'm using it to help build the business.",
      "I've worked through equipment inventory, storage architecture, file migration, NAS reliability, digital-asset protection and operational documentation.",
      "That distinction matters to me. It is easy to reduce AI to \"write me a caption.\" There is nothing wrong with that. I do it too.",
      "But things became much more interesting when I stopped looking at AI simply as a writing machine and began using it as something closer to a collaborator, analyst and occasionally an intellectual sparring partner.",
      "## Then We Started Building Provenance",
      "Photography has entered an interesting period. A photograph can now be captured, computationally processed, retouched, altered, generated or some combination of all five.",
      "That creates a question I believe photographers and clients are increasingly going to care about: what exactly am I looking at?",
      "Photography Fit 2 Print has been developing a provenance system around that question. We have been working through an append-only ledger, XMP-first evidence gathering, cryptographic hashing, asset and master relationships, print records and rules surrounding generative content.",
      "Machines can gather evidence. Machines can propose classifications. But I have established an important boundary:",
      "> A machine should not silently make a material claim about the authorship or provenance of my artwork.",
      "There is still a human being responsible for the work. Me.",
      "That principle may eventually prove more important than the technology underneath it.",
      "## AI Has Also Been Helping Me Write",
      "I'm also working on a book. AI has helped me with continuity, structure, editing and occasionally figuring out what I am actually trying to say.",
      "But I don't want AI writing a book and attaching my name to it. There is a difference between helping me find the sentence and inventing the experience behind the sentence. Those experiences belong to me.",
      "Sometimes the most useful interaction I've had with AI ends with me saying: \"No. That isn't what I'm trying to say.\"",
      "That may sound like failure. It isn't. Sometimes having something reflected back at you makes your own position clearer.",
      "## I Use It in My Other Professional Life Too",
      "Photography is not my only professional discipline. I come from project controls and scheduling, so I've also used AI to examine employment opportunities, review my resume, evaluate how my experience aligns with positions, prepare for interviews and organize CAPM study material.",
      "That background has probably influenced how I'm approaching AI more than I initially realized. Project controls teaches you not to become impressed simply because something is moving. You want to know: What is the scope? What is the baseline? Who owns the decision? What changed? What is the impact? Where is the risk?",
      "AI deserves exactly the same questions.",
      "## Now Let's Talk About What Didn't Work",
      "There was a Photography Fit 2 Print campaign poster. It was terrible. Not mediocre. Terrible.",
      "I supplied finished photographs that I considered completed pieces of artwork. During the design process, those photographs effectively became raw material to be manipulated.",
      "I hated the result. We stopped. But something useful came out of it. I established a rule:",
      "> My photographs are finished artwork unless I explicitly authorize their alteration.",
      "That failure produced an operating standard. And that might be one of the most important things AI has done for my business.",
      "## Failure Can Reveal the Rule",
      "There have been smaller failures too. AI can over-polish my writing. Suddenly something I said sounds technically perfect but doesn't sound anything like me. My humor disappears. My cadence disappears. My lived experience gets replaced by something that sounds like it came from a conference-room presentation. No thank you.",
      "AI can also move toward execution too quickly. The provenance work has reinforced something I already understood from project controls:",
      "> Establish the rules before you automate the process.",
      "Authority first. Evidence second. Controls in place. Then automation.",
      "AI also has a tendency to give you fifteen good ideas simultaneously. That sounds wonderful until you realize you haven't fully understood idea number two and you're already saying yes to number eleven.",
      "Again, project controls. Scope it. Sequence it. Understand the dependencies. Then authorize the work.",
      "## Maybe We're Asking the Wrong Question",
      "Most conversations about artificial intelligence begin with: what can AI do? I'm beginning to think a more useful question for a business owner might be:",
      "> Where did AI fail, and what did that failure teach me about my business?",
      "The failed poster taught me something about artistic authorship. The provenance project taught me something about human authority. The NAS work taught me how easily technology can create a false sense of security. The writing taught me the difference between polish and voice.",
      "Those are not AI tricks. Those are governance lessons.",
      "## An AI Policy We Never Intended to Write",
      "One unintended consequence of all this is that Photography Fit 2 Print appears to be developing an AI policy without ever sitting down and declaring, \"Today we're going to write an AI policy.\"",
      "Instead, the policy is emerging from the work. Authorship matters. Provenance matters. Finished artwork should remain finished artwork. Generative content should be disclosed appropriately. Machines can gather evidence and make recommendations, but material decisions require human accountability. Technology should support the creative process rather than quietly taking ownership of it. Archival integrity matters. And just because something can be automated doesn't mean it should be automated.",
      "I didn't begin experimenting with AI expecting to arrive here. I was trying to become more efficient. Instead, the technology has forced me to become more specific about what Photography Fit 2 Print actually believes.",
      "And perhaps that is one of the most valuable things a new technology can do. It forces you to decide where you stand.",
      "> We are Fit 2 Capture. We are Fit 2 Curate. We are Fit 2 Print.",
    ],
  },
  {
    slug: "nas-storage-is-not-security",
    title: "NAS: Storage Is Not the Same as Security",
    excerpt:
      "Owning a Network Attached Storage box for two years taught me the hard way that redundancy, backup, and security are related concepts — but they are not the same thing.",
    date: "2026-08-16",
    content: [
      "First of all, this is not a retrospective on Nasty Nas from Queensbridge in my beloved Queens, New York. We are not about to spend the next ten minutes arguing about Jay-Z, Nas and The Notorious B.I.G. and who deserves to be called the best rapper alive.",
      "Although, for the record, I am apparently still close enough to relevance to know that this argument can ruin an otherwise perfectly good afternoon.",
      "I'm here to talk about a different NAS: Network Attached Storage.",
      "About two years ago, I invested in one.",
      "Silly me decided I could do the whole thing myself, armed with an unhealthy number of YouTube videos, a little confidence and just enough technical knowledge to become dangerous.",
      "At first, everything looked right.",
      "The drives were there. My files were there. I could access my photographs across the network. There were multiple disks spinning away inside a box that looked considerably more sophisticated than the external hard drives I had used for years.",
      "It felt safe.",
      "> That word matters.",
      "> Felt.",
      "Because one of the things I eventually learned is that storage, redundancy, backup, archival protection and security are related concepts, but they are not the same thing.",
      "## So What Is a NAS?",
      "At its simplest, Network Attached Storage is a dedicated storage system connected to your network rather than directly attached to one computer.",
      "Think of it as your own private file server.",
      "Instead of having photographs scattered across a laptop, desktop, external hard drives and whatever other device you forgot you copied them to, a NAS can provide a central location where authorized computers and devices can access those files.",
      "Depending upon how the system is configured, it can also provide drive redundancy, automatic backups, file synchronization, user permissions, remote access, versioning and other protections.",
      "That sounds wonderful.",
      "And it can be.",
      "But there is an important sentence hidden inside that paragraph:",
      "Depending upon how the system is configured.",
      "Owning a NAS does not automatically mean your files are backed up.",
      "Having multiple drives does not automatically mean your photographs are protected from deletion.",
      "RAID does not magically protect you from ransomware, fire, theft, accidental overwriting, corrupted files or a human being sitting at the keyboard making a terrible decision.",
      "I learned that there is an enormous difference between owning storage equipment and having a storage strategy.",
      "## Photographs Are Assets",
      "That distinction became increasingly important to me because Photography Fit 2 Print has grown beyond simply taking pictures.",
      "We capture.",
      "We curate.",
      "We edit.",
      "We print.",
      "We archive.",
      "And increasingly, we are thinking seriously about provenance — knowing where an image came from, what happened to it during the creative process, which version became the finished artwork and how that work should be preserved.",
      "Those files are not clutter sitting on a computer.",
      "They are business assets.",
      "More importantly, many of them are memories that cannot be recreated.",
      "A client portrait can be photographed again.",
      "Sometimes.",
      "A wedding cannot.",
      "A photograph of someone who has passed away cannot.",
      "That perfect expression, that family gathering, that performance, that trip, that moment when the light fell exactly where it needed to fall — those things do not care whether your hard drive failed.",
      "They are simply gone.",
      "That changed the way I began looking at storage.",
      "## The False Sense of Security",
      "I think this is where many photographers, artists and small businesses can get caught.",
      "We buy another hard drive and feel safer.",
      "Then we buy a NAS and feel even safer.",
      "There are four drives inside instead of one, so mathematically that has to mean we are four times safer, right?",
      "> Not necessarily.",
      "Redundancy can protect you from certain hardware failures. That is valuable.",
      "But redundancy is not necessarily backup.",
      "Backup is not necessarily disaster recovery.",
      "And having a backup sitting three feet away from the NAS may not help very much if something happens to the entire room.",
      "That was the part I had not fully understood when I began.",
      "YouTube had given me a collection of answers.",
      "What I did not yet have was an architecture.",
      "## This Time, We Built a System",
      "The NAS project eventually became something much larger than installing hard drives.",
      "We approached it as infrastructure.",
      "My photography archive had to be migrated. The network had to work reliably. The original files had to remain protected. We had to think about what could be automated, what required human confirmation and what information should follow an image throughout its life.",
      "And I am proud of what our team has accomplished.",
      "That word team is intentional.",
      "Some of the work involved hardware. Some involved software. Some involved artificial intelligence helping us investigate, document and test different approaches. And some required the one thing technology still cannot replace: a human being deciding what matters.",
      "We built the system around that distinction.",
      "Machines can gather evidence.",
      "Machines can check files.",
      "Machines can identify metadata.",
      "Machines can compare hashes and flag inconsistencies.",
      "But when something becomes part of the authoritative history of one of my photographs, I want a human decision involved.",
      "> Mine.",
      "Technology assists the process.",
      "It does not own the artwork.",
      "## The NAS Is Working",
      "Today, the files have been migrated.",
      "The NAS is operating across the network with very few issues.",
      "That sentence sounds almost boring.",
      "I love that.",
      "Infrastructure should eventually become boring.",
      "I don't want to wake up every morning excited because my storage array survived another night. I want to make photographs. I want to print. I want to work on Photography Fit 2 Print. I want the technology underneath those activities to quietly do its job.",
      "Getting there required learning something I wish I had understood two years ago:",
      "Buying a NAS is not the end of the storage conversation. It is the beginning of one.",
      "Before purchasing one, ask questions beyond how many terabytes it holds.",
      "What happens if a drive fails?",
      "What happens if two drives fail?",
      "What happens if you accidentally delete a folder?",
      "What happens if malware reaches the system?",
      "Where is the second copy?",
      "Is there an off-site copy?",
      "Can previous versions of a file be recovered?",
      "Who has permission to delete something?",
      "How will you know whether the backup actually worked?",
      "And perhaps the most uncomfortable question:",
      "> Have you ever tested whether you can get your files back?",
      "Because a backup you have never restored is partly an act of faith.",
      "## I Am Not Here to Sell You a NAS",
      "I am not telling you which box to buy.",
      "I am not telling you that everybody needs one.",
      "And I am certainly not pretending that two years of ownership suddenly made me a network-storage engineer.",
      "What I can share is the experience.",
      "I can tell you that I originally confused having more storage with having more protection.",
      "I can tell you that I underestimated how much planning should happen before the drives ever receive the first photograph.",
      "And I can tell you that once you begin treating photographs as long-term creative assets instead of disposable computer files, your entire attitude toward storage changes.",
      "That may lead you to a NAS.",
      "It may lead you somewhere else.",
      "But whatever solution you choose, understand what it protects you from — and just as importantly, what it does not.",
      "Because somewhere on one of those drives might be a photograph you don't yet realize will become priceless.",
      "> Protect it accordingly.",
      "And now that we have settled that…",
      "We can get back to the much easier question.",
      "> Nas, Jay-Z or Biggie?",
    ],
  },
  {
    slug: "the-photograph-that-time-will-choose",
    title: "The Photograph That Time Will Choose",
    excerpt:
      "No photographer presses the shutter with certainty — but every image deserves the craftsmanship worthy of an unknown future.",
    date: "2026-08-07",
    content: [
      "No photographer presses the shutter with the certainty that this will be the image future generations refuse to let fade.",
      "History never identifies its favorites in advance.",
      "The photograph destined to outlive us rarely announces its importance the day it is created.",
      "More often, it slips quietly into existence unnoticed. It is the unguarded laughter around the dinner table, a father’s weathered hands resting on a child’s shoulder, a mother’s comforting embrace, the gap-toothed grin that disappears before anyone realizes how fleeting it was, or two grandparents sharing an ordinary afternoon that seemed too commonplace to matter.",
      "Yet time possesses an extraordinary gift.",
      "It elevates the familiar into something irreplaceable.",
      "The image overlooked today may become the one your children safeguard with quiet devotion. The framed portrait you pass without a second glance may someday inspire your grandchildren to ask, “Who were they?” A weathered album tucked away on a bookshelf may eventually become the final refuge for a smile, an expression, or a face that no longer exists anywhere else.",
      "None of us can foresee which frame will carry that burden.",
      "That uncertainty is precisely why every photograph deserves unwavering intention.",
      "Every exposure deserves patience.",
      "Every finished image deserves craftsmanship worthy of its unknown future.",
      "Not because each photograph belongs beneath gallery lights, but because any single frame may one day shoulder the weight of a family’s story. Long after names have faded from memory, photographs often become the bridge that reconnects generations separated by decades.",
      "As photographers, we are never granted the luxury of deciding which images will matter half a century from now. That judgment belongs to time alone. Our calling is far simpler—and far more demanding.",
      "We create every photograph as though it could become someone’s most treasured possession.",
      "That conviction is the heartbeat of Photography Fit 2 Print.",
      "It is more than a business name. It is a promise. A promise that every photograph leaving the studio has been crafted with the respect future memories deserve. Images intended not merely to exist on a screen, but to live on walls, rest in albums, pass through careful hands, and be rediscovered by people we will never meet.",
      "Because heirlooms are not born the moment the shutter closes.",
      "They earn that distinction one generation at a time—through remembrance, through preservation, and through the enduring affection of those who refuse to let the story disappear.",
    ],
  },
];
