import type { BlogPost } from "@/lib/blog-posts";

export const EXTRA_BLOG_POSTS: BlogPost[] = [
  {
    slug: "an-extraordinary-collection-of-beginnings",
    title: "An Extraordinary Collection of Beginnings",
    excerpt:
      "I asked AI to stop helping me make things and look instead at the record of what I had already been doing. What emerged was an uncomfortable question about ideas, concentration, unfinished work, and what happens when curiosity is allowed to interrupt everything.",
    date: "2026-08-31",
    seoTitle: "An Extraordinary Collection of Beginnings | Behind the Print",
    metaDescription:
      "John Guest examines a pattern hidden inside years of projects, photography and ideas, then begins a 30-day experiment to find out what changes when fewer things receive more attention.",
    tags: [
      "Behind The Print",
      "Creative Process",
      "Photography",
      "Focus",
      "Personal Reflection",
      "Bloomington Public Library",
    ],
    image: "/photos/John-and-AI-Beginnings-Store-Hero-web.JPEG",
    imageAlt:
      "Illustrated John in his power wheelchair holding a seedling package while the AI character pushes a cart overflowing with photographs, notebooks, cameras and unfinished ideas beneath a Beginnings sign.",
    imageCaption: "Apparently, we’re buying all the beginnings.",
    imageCredit: "AI-assisted artwork for Photography Fit 2 Print.",
    imageWidth: 1672,
    imageHeight: 941,
    content: [
      "I've accumulated enough conversations with AI that something interesting has started to happen. There is a record now. Not just of the questions I've asked, but of projects I've started, photographs I've worked on, things I've finished, things I've changed my mind about and ideas that were apparently important enough for me to spend three hours discussing before another idea showed up.",
      "So I decided to use that record differently.",
      "Instead of asking AI to help me make something, I asked it to look at what I had already been doing and tell me what it saw.",
      "I wasn't particularly interested in compliments. I wanted the patterns.",
      "There was plenty of material. Photography Fit 2 Print alone has generated conversations about portraits, community photography, restoration, printing, competitions, the website, business systems and the provenance work I've been developing to document what happens to my photographs. Then there's Behind the Print, my interest in teaching, the Bloomington Public Library and its Innovator-in-Residence program, and some serious thinking I've started doing about legacy.",
      "On paper, that's a lot.",
      "Maybe too much.",
      "That was one of the first things the analysis exposed.",
      "## Busy Is Not the Same as Focused",
      "I have spent a good portion of my professional life in project controls. Give me a complicated problem and my instinct is to start figuring out how the pieces relate. What happens first? What depends on what? Where are the risks? What needs to be controlled?",
      "Apparently I brought that guy with me into photography.",
      "It has been useful. Photography Fit 2 Print isn't being built entirely on improvisation. I'm thinking about the photographs, but I'm also thinking about what happens to them afterward. How they're edited. How they're printed. How they're stored. How their history is preserved. How somebody other than me might eventually understand what they're looking at.",
      "The problem is that I can do the same thing with an idea.",
      "An idea shows up and pretty soon I can see what it could become. Then I see what would be required to make it work properly. That reveals another possibility. Before long, something that started as a simple thought has architecture.",
      "The strange part is that this doesn't feel like procrastination because I'm not sitting around doing nothing. I'm usually working pretty damn hard.",
      "That may be exactly why it took me a while to recognize the problem.",
      "There is a difference between being busy and concentrating effort long enough for something to compound.",
      "I have plenty of evidence of the first one.",
      "I want more evidence of the second.",
      "## I Thought I Had Several Different Interests",
      "Another part of the analysis surprised me.",
      "Photography, printing, restoration, writing, teaching, archiving, provenance and legacy planning can look like separate pursuits. I've occasionally wondered whether I'm trying to make Photography Fit 2 Print carry too many ideas.",
      "Maybe I am. That question isn't settled.",
      "But when I stopped looking at the labels and looked at what I actually do, I noticed something connecting a lot of them.",
      "I care about what survives.",
      "That shows up very literally in restoration. An old photograph may be damaged, noisy, faded or technically limited, but the reason somebody cares about it usually has very little to do with pixels. Somebody they love is standing in that picture.",
      "It shows up in printing too. I have never been particularly interested in photography ending as another image somebody scrolls past. There is something different about making an object that can live on somebody's wall.",
      "The provenance work takes the same instinct into a much more technical direction. If a photograph matters, I want to know where it came from, what happened to it and what was changed. That became even more important to me as generative AI started complicating what a photograph can mean.",
      "Behind the Print may be another version of the same thing. I'm not only interested in showing the finished photograph. Increasingly, I want to preserve some record of what was happening around it.",
      "That doesn't mean I've discovered some grand unified theory of myself. I'm suspicious of conclusions that neat.",
      "But there is enough evidence for me to keep following the thread.",
      "## Then the Analysis Got Uncomfortable",
      "One observation bothered me because I recognized it immediately.",
      "Starting something can be rewarding.",
      "There is possibility in a beginning. Nothing has failed yet. Nothing has disappointed you. The thing in your head can still become everything you imagine it might be.",
      "Finishing changes the relationship.",
      "Eventually the photograph has to be shown. The application has to be submitted. The article has to be published. The service has to encounter an actual customer. Somebody besides me gets a vote.",
      "I don't think I'm afraid of criticism. I've had enough life and enough professional experience to survive somebody not liking my work.",
      "But I do think I enjoy possibility, and I may enjoy it enough that I sometimes give the next possibility attention that belongs to something already underway.",
      "That's a different problem.",
      "And if I'm right about it, another planning exercise isn't going to fix it.",
      "## What Repetition Can Do",
      "This is where photography gives me a useful way of thinking about the problem.",
      "I can go downtown one Saturday and make some photographs. Maybe I get something beautiful. Maybe I meet somebody interesting. That's worthwhile on its own.",
      "But what happens if I keep going?",
      "What happens if I photograph the Bloomington Farmers Market for five years?",
      "People change. Vendors change. Downtown changes. Buildings change. Somebody I photographed once becomes somebody I've photographed twenty times. A collection starts developing relationships that no individual photograph could contain.",
      "Time starts contributing to the work.",
      "I can't manufacture that in Lightroom.",
      "The same thing applies elsewhere. One restoration is one restoration. One essay is one essay. One print is one print. Enough deliberate work, finished consistently over time, starts becoming a body of work.",
      "That's where I think I've been leaving something on the table.",
      "Not because I haven't been working.",
      "Because accumulation requires staying with things after the excitement of discovering them has worn off.",
      "## A Thirty-Day Experiment",
      "The timing of all this is interesting because I have something sitting directly in front of me.",
      "I've been considering applying for the Bloomington Public Library's Innovator-in-Residence program.",
      "The ideas are already developing. I've been thinking about teaching photography through observation, light, composition, connection and dignity. I've been thinking about what it means to teach somebody to see rather than simply teach them how to operate a camera.",
      "Normally, I could probably turn that into six additional projects before lunch.",
      "I'm going to try something different.",
      "For the next 30 days, the application gets finished.",
      "That doesn't mean Photography Fit 2 Print shuts down. I'm still going to photograph. Existing work still exists. Life still gets a vote.",
      "It means a new idea doesn't automatically earn the right to interrupt something I've already decided matters.",
      "I can write the idea down.",
      "It can wait.",
      "That sounds ridiculously simple when I read it back.",
      "Maybe it is.",
      "## I Want the Evidence",
      "One thing I don't want to do is write the ending of this story before I've lived it.",
      "I don't know whether concentrating my attention this way will produce dramatically different results. I don't know whether the library will select me. I don't know whether I'll discover that some projects I've been protecting should actually be abandoned.",
      "That's the useful part.",
      "Thirty days from now there will be data.",
      "Did I submit the application?",
      "What else did I finish?",
      "What did I choose not to start?",
      "Did anything important suffer because I narrowed my attention?",
      "Did I feel constrained, or did I finally give myself enough room to work?",
      "Those answers interest me more than another theory about productivity.",
      "I'm 59. I don't say that because I think the clock is about to run out. I say it because I've lived long enough to understand that time is an actual resource.",
      "I've spent a career managing resources.",
      "Maybe it's time I became a little more disciplined about this one.",
      "There are still a ridiculous number of things I want to photograph, make, learn, write and experience. I'm not interested in becoming less curious to make myself more efficient.",
      "I'm interested in finding out what happens when curiosity stops getting automatic authority over concentration.",
      "So that's the experiment.",
      "I'll keep the ideas.",
      "I'm just going to make them wait their turn.",
      "And in 30 days, instead of asking what I think about it, I'll look at what I finished.",
      "Photography Fit 2 Print",
      "> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
    ],
  },
];
