both of them.",
      "That tiny change creates an entirely different photograph for me.",
      "The first image feels like a question about temptation.",
      "The second makes me wonder whether the decision has already been made.",
      "And here’s the important part.",
      "Reblum didn’t create that.",
      "That happened between Claire, the snake, the environment, my camera and me when I pressed the shutter.",
      "The software came later.",
      "That distinction is becoming my test for AI-assisted tools in photography: Does the tool help me finish my photograph, or does it start trying to become the photographer?",
      "So far, what interests me about Reblum is the possibility of incorporating it into a process I already understand.",
      "Capture still matters. Light matters. Expression matters. Curation matters. Retouching matters. And knowing when to stop matters.",
      "The software can help with the labor.",
      "It doesn’t get the final say.",
      "That belongs to me.",
      "Eventually there is one more test these photographs have to pass.",
      ">> The Paper.",
      "I want to see those deep reds and blacks come out of my printer. The olive green. Claire’s skin against that darkness. Those soft pink flowers. And the extraordinary pattern of the snake moving through the composition.",
      "Because around here, an image isn’t finished simply because it looks good on a screen.",
      ">>> Fit 2 Capture. Fit 2 Curate. Fit 2 Print.",
      "Model: Claire Rieger / Snake: Michael Beran / Event: ShutterFest 2024 — Day Zero / Photography: Photography Fit 2 Print / John Guest",
      "Disclosure: I’m a Reblum affiliate. If you decide to try Reblum through my affiliate link or code ([reblum.app/p/TID.2934](https://reblum.app/p/TID.2934)), I may receive a benefit from the referral. These are my photographs and my opinions about how Reblum fits into my own retouching workflow.",
    ],
  },
  {
    slug: "behind-the-print-learning-how-we-work",
    title: "Behind the Print: Learning How We Work",
    excerpt:
      "A look back at the early friction of building an AI-assisted photography workflow, and what changed once memory stopped being mistaken for knowledge.",
    date: "2026-09-19",
    seoTitle: "Behind the Print: Learning How We Work | Behind The Print",
    metaDescription:
      "John Guest reflects on the early friction of building an AI-assisted photography workflow, the difference between memory and knowledge, and where creative judgment still belongs to the photographer.",
    tags: ["Behind The Print", "Photography Workflow", "AI-Assisted Creativity", "Personal Reflection"],
    content: [
      "There was a point where all of this felt a lot more complicated than it does now.",
      "Not because the technology was necessarily difficult, but because we were still learning each other. I was learning what AI could actually help me with, what it was good at, what it was terrible at, and where I still needed to keep my own hands firmly on the wheel. At the same time, I was trying to figure out how to build something that supported my photography without turning the technology itself into the main attraction.",
      "There were some bumps. Actually, there were a lot of bumps. Files ended up in the wrong place. Instructions got misunderstood. Things I thought were obvious were not obvious at all. Sometimes the system moved too fast. Sometimes I expected too much. Sometimes I had to stop everything and say, “No. That is not what I meant.”",
      "And somewhere along the way, that became part of the process.",
      "What started as conversations about cameras, lighting, editing, and printing slowly became something more useful. We started building a working environment around the photography itself.",
      "Camera manuals stayed available when I needed to check a setting instead of trusting my memory. Lighting information became something we could return to rather than rediscover every time. Critiques started becoming less about whether someone “liked” the picture and more about what I was actually trying to accomplish. Intent, composition, light, color, texture, emotion, and print all became part of the conversation.",
      "The questions got better, and when the questions got better, the work started getting better too.",
      "One of the biggest lessons for me was learning that memory and knowledge are not the same thing. Just because a system remembers something does not make it true. Just because we discussed something three months ago does not mean it should become gospel.",
      "That realization changed the way I started thinking about this whole relationship.",
      "If Canon says something about the R5 Mark II, I want the Canon manual. If I am troubleshooting a lighting setup, I want the specifications and the results from the actual test. If I am reviewing competition work, I want the scorecard and the notes. If I am talking about what makes a photograph successful, then I want my own experience and judgment in that conversation too.",
      "And if AI is making an educated guess, I want to know that it is a guess.",
      "That distinction matters to me.",
      "Photography has always been full of opinion. Somebody likes contrast. Somebody else wants everything soft. Somebody wants more detail. Somebody thinks the crop should have been different. That is part of art.",
      "But technical facts are different. If I am going to build a workflow around something, I want to know where the information came from.",
      "Over time, that has become one of the strongest parts of what we are building together. I do not need AI to pretend it knows everything. I need it to help me organize what I know, find what I do not know, challenge me when something does not make sense, and stay out of the way when the creative decision belongs to me.",
      "That balance took some work. There were moments when I treated the techn